fetch.sh
Summary of the WM madness going on here:
If the user has not exported the environment var `windowmanager` (in which case there is no need to overwrite it temporarily, it's already defined), then the script checks if `wmctrl` is installed. If not, it checks if `.xinitrc` exists. If it does, it greps the exec line. Otherwise, it gives up.
=> Fix capitalization and add better window manager detection.

fetch.sh
A simple addition to add support for counting packages under Void Linux, by using xbps, Voids package manager.
=> Add support for Void Linux

1.1.md
It seems Dylan's using [grip](https://github.com/joeyespo/grip) for markdown previewing.
=> Fixed a mistake in the changelog.

fetch
This rewrite of the theme detection fixes cases where the gtk theme is 
incorrectly displayed due to the DE not writing `.gtkrc` files etc.
I've opened this PR to see if anyone has any ideas/queries about this before 
it gets pushed to master.
This is pretty much done, all that's missing is KDE support  and 
some error detection which I'm working on as we speak.
=> Rewrite GTK theme detection to also get correct DE theme.

README.md, config/config, fetch
IP support is done in my eyes.
I've tested this PR with these OS and it works fine without issues.
- 8 linux distros
- 3 BSD distros
- Windows 7 
Before I push this to master I'd you guys to test this out!
You can test it by swapping to the `ip` branch and adding these 
lines to your printinfo function:
```sh
info "Local IP" localip
info "Public IP" publicip
```
If you guys have any suggestions for features/changes now is 
the time to speak up.
=> IP Address support

fetch
Before this fix, if the uptime was under a minute, it showed as `Uptime: up`. You don't say?
=> Fixed uptime output when the uptime is under a minute

config/config, fetch
`getgtk` is now a generic theme function and now supports KDE.
- Added support for getting KDE theme.
- Renamed `getgtk` to `getstyle`.
- Renamed `getgtktheme` to `gettheme`.
- Renamed `getgtkicons` to `geticons`.
- Renamed `getgtkfont` to `getfont`.
- Changed `GTK Theme` title in printinfo to `Theme`.
These changes were made because the function now also supports
KDE which is based on QT and the naming/titles are misleading.
You'll need to update your config file due to the new function names. 
```sh
info "GTK Theme" gtktheme
info "Icons" gtkicons
info "Font" gtkfont
info "Theme" theme
info "Icons" icons
info "Font" font
```
Let me know what you guys think.
=> getgtk changes

1.2.md, README.md, fetch
I did an strace of `wmctrl -m` and it turns out that it gets the window 
manager name from `_NET_WM_NAME`.  I did some googling and we 
can use xprop to get the value of `_NET_WM_NAME` which means
that we can swap the dependency from wmctrl to xprop.
xprop is available almost everywhere which means that users running
X under Mac OS X and Windows will now get the window manager info
too!
I'm currently going through VMs testing this change but it seems like
it should work anyway.
=> Use 'xprop' instead of 'wmctrl' to get the window manager.

1.3.md, README.md, config/config, fetch
The user no longer has to set the `font_width` value, fetch calculates it using
terminal size and number of columns/lines.
This change also makes image sizing take terminal height into account, this
fixes issues with terminals where the height is far lower than the width. 
This seems to work in all terminal emulators and font sizes I've tried but I'd
still like some people to test it out!
Thanks
=> Font size is now calculated by fetch

fetch
The Windows visual style is now a part of `getstyle`.
If `X` is running then the `DE` / `GTK Theme` is used, otherwise we use the Visual Style.
=> Merge `getvisualstyle` with `getstyle`.

1.3.md, config/config, fetch
This PR cleans up the `--stdout` functions and removes support for printing all
functions using `--stdout` without args as it was messy and slow.
=> Cleanup 'stdout' functions

README.md, config/config, fetch
This PR changes the way we set text and ascii colors allowing us to
set the text to distro colors in any image mode.
By default text will be colored according to your distro's logo colors 
no matter what image mode you're in. The current implementation 
in master only works when the user is in `ascii` mode.
This PR removes all of the `*_colors` options and replaces them 
with a single `colors` variable and flag. For example:
```sh
colors=(1 2 3 4 5 6)
colors=(distro)
```
Using `--colors` with no arguments will now disable text colors
entirely. (`fetch --colors`)
Another cool feature is that when `$colors` is set to distro and you
change `--ascii_colors` or `$ascii_colors` to a custom value the text
changes with it.
I'm still working on this but it's pretty much complete, let me know
what …
=> Changes to text and ascii color handling

neofetch
Fixes #112.
Rationale:
- By default in Slackware, /sbin and /usr/sbin aren't part of the user's
PATH. (It's been this way since I started using it in 2004, version
9.1)
- `type -p /path/to/binary` works just like it was used with a bare
binary name.
=> Fix 0 package count in Slackware

README.md
HTTPS is not working in apt without additional package called `apt-transport-https`
=> small change (apt does not support https by default)

neofetch
Fixes `Which Distro\'s ascii art to print` in output when running `--help`. (Notice the backslash-quote.)
Caused by a rogue backslash in the heredoc.
Aside: I don't think Github's syntax highlighting is doing a good job here.
=> Fix help message text

config/config, neofetch
This PR reimplements `--stdout_separator` for use with `--stdout`. 
Please test it out and let me know if there are any issues.
=> Reimplement '--stdout_separator'

neofetch.1
For some people (including me, I guess), `screenfetch --help` is a bit... inconvenient, because you have to scroll your mouse to find your desired option, and some of us want to be as mouse-free as possible, so I thought that man page would be beneficial, so you can find it easily, scroll-free.
I don't know how other distros/CRUX port/Gentoo ebuilds will handle this, but in AUR you'll have to add this into the PKGBUILD's `package()`:
install -Dm644 "neofetch.1" "$pkgdir/usr/share/man/man1/neofetch.1"
=> man pages?

1.5.md, README.md, config/config, neofetch, neofetch.1
removes 'Graphics', 'GeForce' and 'Radeon' from output
as I have intel and nvidia graphics in my system, i was finding the output was wrapping for me. this fixes it, thought i'd share it with `master`
=> added tiny option to --gpu_shorthand

README.md
Added another repo for CentOS.
Since RHEL and CentOS do not use dnf (they're based
on Fedora 19), we need to use separate instructions
for now. Although this package is originally
intended for CentOS, but since CentOS is basically
RHEL without RH's trademark, it will be the same.
But I can't say the same for Scientific Linux or
Oracle Linux, even if both of them are based on RHEL.
=> Added installation instructions for RHEL and CentOS

neofetch
- disk usage bar didn't work on drives under a terabyte
- disk usage percentage still printed when disabled
- battery info option was inversed
=> fixed a few issues with the progress bars

neofetch
apparently bar doesn't like it when the first variable is bigger than the second, it went really haywyre.
to see old behaviour, set `disk_used` to `63` and `disk_total` to `3.1` (that's what my disk usage and disk total is, in gigabytes and terabytes respectively)
=> fixed output of disk bar when gigabytes are used of a terabyte disk

neofetch
it would always print the OS X build version before because the option wasn't parsed before adding the build. Now it's removed after the fact if it needs to be.
=> fixed osx_buildver option

neofetch
Fixed the awk string to terminate after grabbing the first wallpaper found in nitrogen instead of mixing the two strings together and using the ascii art instead. In later revisions, there should be a way to check it's using the current monitor's wallpaper (I don't believe nitrogen orders them by usage, but rather by output).
=> Fixed wallpaper error with nitrogen

neofetch
This PR adds a new var called `stdout_mode` that is set to `on` when stdout mode is used. This allows us to change options when stdout mode is used.
=> Fix stdout mode when used with functions that use prin

neofetch
CRUX has a binary called crux that print the distro name and the version (CRUX version 3.2 for example).
=> Update CRUX distro name

config/config, neofetch
Scrot_fixes
- Fixes **#161**.
- Scrot filename now uses `date` to work with other programs.
**NOTE**: `scrot_dir` now needs to end with a `/`.
```sh
scrot_dir="$HOME/Pictures/"
scrot_dir="$HOME/Pictures"
```
I'll merge this once people have tested that it works.
cc @Brottweiler
=> Fixed bugs with scrot usage

neofetch
In my case your `if pgrep "mpd" >/dev/null 2>&1` is not working because i'm using mpd on server and mpc on my laptop, so i don't have mpd on it and `pgrep` is failing. I think it is better to search for mpc than for mpd in this `if`
=> fix for mpc detection

README.md, config/config, neofetch, neofetch.1
This PR removes the shuffle mode and all the config options and flags that came with it and replaces it with `--image path/to/dir/` and `image="path/to/dir/"` instead. 
- This will hopefully clear up the confusion in issue **#169**.
- You can set the default shuffle dir in the config by changing `$image` to a directory path.
- The value **must** end in a `/`.
TODO
I'd like to get some confirmation that this works on other platforms before I merge this to master.
cc @misterch0c @iandrewt
=> Remove shuffledir in favor of '--image path/to/dir/'

neofetch
This PR changes the escape sequence we're using for coloring to something that works on a lot of older operating systems too. This also clears the coloring beforehand which fixes some other bugs
related to color I've found.
=> Fix colors in older versions of Mac OS X, OpenBSD etc

README.md, config/config, neofetch, neofetch.1
Display refresh rate with `--refresh_rate on`
TODO:
This closes **#159**
=> display refresh rate after each monitor (optional)

neofetch
the `&& \` method doesn't work with `elif`s it seems. breaks the script on OS X even though that block of code never fires.
=> fixed if statement for linux resolution

neofetch
This rewrite makes the memory function work on old linux kernel versions while also reducing the size of the function to 3 lines.
- This fixes the issue inside  **#152**
cc @joshbenham
=> Rewrite memory function to work on older linux kernel versions.

neofetch
I export GTK2_RC_FILES to $XDG_CONFIG_HOME/gtk-2.0/gtkrc (as specified in the [Arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support)) to help keep my home folder clean.
This way neofetch uses GTK2_RC_FILES if it is set, and the default location if it is not.
=> Use $GTK2_RC_FILES for GTK2 config if set

1.6.md, neofetch
This PR aims to cleanup all of the info functions, reduce the amount of space they take up and hopefully speed things up as a bonus.
Functions cleaned up so far:
- Distro
- Uptime
- CPU
Issues fixed:
- Missing ascii colors for `Puppy Linux`.
- Fixed disk usage not working on `FreeBSD`.
- Fixed broken CPU speed when using `/proc/cpuinfo` instead of `/sys/`.
Changes: 
- Functions now no longer print `Unknown` when they fail, they now don't print anything.
- `Song` now displays `Not Playing` instead of `Unknown` when no music player is found.
=> Info function cleanup

1.6.md, config/config, neofetch
Implement WM Theme
Features:
- Implements Window manager theme support.
- Changes all usage of `$HOME/.config` to `XDG_CONFIG_HOME` with a fallback to `$HOME/.config`
Changes:
- Moved Windows theme detection to WM Theme instead of getstyle.
TODO:
=> Implement Window Manager Theme

config/config, neofetch
- Fixes #215 
- Removes duplicate blocks from function.
- Fix architecture issue with arm CPUs.
- Fix `xprop` error in DE detection when X isn't running.
TODO
- Needs testing on 
cc @derphilipp, can you test this PR? (Just let me know if it fixes the issue.)
=> CPU / Distro / DE fixes.

neofetch
This breaks up the package `if` block into individual blocks which will allow 
the package count to work with multiple package managers. This will also 
help out with adding bedrock linux support!
TODO
- ~~Add up the result from each package manager.~~
- ~~Testing~~
Fixes **#228**.
=> Fix issues with users having more than one package manager installed.

neofetch
This PR aims to fix issues with the OS X and BSD part of the uptime function.
Changes
- $mins is now $minutes
- Fixes format issues with uptime on OS X and BSD
- Fixes #230 
TODO
- Testing
=> OSX and BSD uptime fixes.

neofetch
This makes the memory function use `memavail` when available.
This is a better replacement (imo) to #233 and #234.
TODO:
=> [Linux / Windows] Memory: Use memavail when available.

ascii/distro/ubuntu-gnome, neofetch
Everything's fine apart from the fact that the ASCII is getting too close to the output. I can see a variable called padding in the [source](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2138) but it doesn't seem like it's being used.
Also, I am trying to add an option for bold ASCII arts. I have a `hack` by changing: `[0-7]) printf "%b%s" "\033[0m\033[3${1}m"` to `[0-7]) printf "%b%s" "\033[1m\033[3${1}m"` on [line 2642](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2642). But that makes everything bold and hence will not honor settings of a user for not using bold.
**I wanted to ask how are you defining the colors for the ASCII?**
=> [WIP] Added better Ubuntu-GNOME ascii art

neofetch
adding a space prevents cmus from showing the "tag artistsort" information in the song title.
this is my first PR ever, apologies if i'm doing it wrong :)
=> prevent 'tag artistsort' from showing up in song title

neofetch
Right now it does not subtract 1 from the total number of files in a directory, so that sometimes it will not find a file and have to fallback to ascii art.
This *should* always fix this.
=> Image directory randomization can go out of bounds

neofetch
I added support for displaying the fish shell version.
I also have a `.bcrc` file that set the `scale` option, so all divides using `bc` have decimal places displayed. That makes for some ugly output. I added "scale=0" before doing the `bc` memory calculation, and it's much cleaner now.
=> Add Fish version and fix BC scale.

neofetch
Previously would print ` - "song name" "song artist"`, now prints `"song artist" - "song name"`
=> fixed song output for cmus

README.md
Since I found out that Fedora, RHEL and CentOS have a pretty much same installation instructions (the difference being `yum` and `dnf` only), I decided to unify the instructions.
=> Unified installation instructions for Red Hat distros

neofetch
previously would only return if song not playing because of a syntax error
=> fixed iTunes song output

README.md, config/config, neofetch, neofetch.1
This adds a new option to `--size` called `none` which disables cropping/resizing the images.
Features:
- `--size none` / `size=none`: Disable cropping and resizing.
- `--crop_mode none` / `crop_mode=none`: Disable cropping.
Issues: 
This fixes #261
=> Add '--size none' to disable cropping / resizing the images.

ascii/distro/windows, config/config, neofetch
This PR introduces two new functions,
`term` - Get the current terminal emulator.
`termfont` - Get the terminal font.
This closes #251.
**Regular Configs:**
**Profile Based Configs:**
We need to figure out how to get the font on a per profile basis. 
**No Configs:**
Font support can't be added as these terminals are configured at compile time.
- This is because the `$PPID` of `tmux` is `systemd` for some odd reason.
- This is because CYGWIN's `ps` command is missing the `-o` flag.
- This has been fixed with an ugly solution imo.
To test this PR just checkout this branch and run neofetch with 
`neofetch --config off`.
=> Terminal Font Function

neofetch
Got it working in one call of `cmus-remote -Q` too :+1:
=> fixed cmus properly, now works regardless of output order

neofetch
Original PR by @aranega at #272.
This is my version of his PR with some changes made.
Changes:
- Fixed some indentation.
- Changed the spacing of parts.
- We now check for `terminology` by seeing if `tycat` outputs any info. (The output of `tycat` is blank outside of terminology) I changed this because running the `term` function is a little excessive tbh.
- Removed the `read` if block and swapped it out for a variable.
- Reduced size of the formatting block below.
TODO:
```sh
if [ "$image_backend" == "tycat" ]; then
lines=${term_size%%';'*}
columns=${term_size%';'*';'*}
columns=${columns#*';'}
font_height=${term_size##*';'}
font_weight=${term_size#*';'*';'}
font_weight=${font_weight%';'*}
term_height=$((font_height * columns))
term_width=$((font_weight * lines))
else …
```
=> Add terminology image support 2

neofetch
Ok, first, sorry guys, I was so focused on how to deal with images in terminology that I totally missed this issue until now.
When no image is set and there is no background image (or a `.xml` is detected) and the image option is set to `wall` (default), neofetch does not fallback on ascii mode.
The issue comes from the line 2310:
if [ ! -f "$img" ] || [ ${#term_size} -le 5 ] && [ "$image_backend" != "tycat" ]; then
as `||` and `&&` have the same priority, bash does not evaluate `[ ${#term_size} -le 5 ] && [ "$image_backend" != "tycat" ]` first.
Solution is simply this
if [ ! -f "$img" ] || ([ ${#term_size} -le 5 ] && [ "$image_backend" != "tycat" ]); then
Once again, really sorry about that... (shame on me)
=> Fix for terminology support: does not fallback on ascii when no wallpaper is found

neofetch
This PR moves all whitespace trimming to a function instead of littering the 
script with all kinds of whitespace removal commands.
TODO:
- Testing
- Remove any missed whitespace removal commands
Bugs:
=> Move all whitespace trimming to a function.

config/config, neofetch
This PR removes `prompt_height` and instead dynamically sets the 
cursor position in image mode.
Before:
After:
TODO:
- Testing
=> Dynamically set cursor position in image mode.

README.md, neofetch, neofetch.1
This PR removes `image_position`.
This option only worked with `w3m-img` and had rendering issues.
I'll consider re-adding this if we can support `iTerm` and `Terminology`.
=> Remove Image position

1.8.md, README.md, config/config, neofetch, neofetch.1
This PR fixes CPU usage on BSD and Windows.
- Fixes CPU usage output on BSD and Windows
- Fixes misleading output on Linux / Mac OS X
- Moves CPU Usage to its own dedicated function
- Trim white-space in stdout mode.
=> Fix CPU Usage

neofetch
I can't test this yet, but unless the output of `sw_vers -productName` has changed then this will work. Can't test until mid July though... unless someone else has a Apple Developer Program subscription and can test it for me.
=> Add support for macOS Sierra

neofetch
Refresh rate no longer prints when OS X reports it as being `0Hz`
=> fixed refresh rate on OS X

neofetch
Support for terminology font name detection is based on the terminology config file. This file is always located here: `~/.config/terminology/config/standard/base.cfg` (https://github.com/billiob/terminology/blob/30cb65625bfa3b9030b80308d76ec2f30b62bd02/src/bin/config.c#L216) and is in a data/binary format. The only way I found (beside coding a dedicated extractor) is to use `strings`. The font name seems to be placed right before the `font.name` string.
strings ~/.config/terminology/config/standard/base.cfg | grep -B1 font.name | head -1
Here are results that could be output:
$ strings ~/.config/terminology/config/standard/base.cfg | grep -B1 font.name | head -1
6x13.pcf
--> (for a bitmap font) and with another font selected
$ strings ~/.config/terminology/config/standard/base.cfg | grep …
=> Add terminal font detection support for terminology

README.md, config/config, neofetch, neofetch.1
Changes:
- Remove `$line_wrap` / `--line_wrap` since changing this from the<br \> 
default value breaks the output.
- In image mode we now use `printf` to enforce a max line width.<br \>
This fixes issues with lines through images. (See screens below)
=> Line wrap changes

neofetch
This PR makes neofetch read custom ascii art files the same way it reads the builtin ascii
files. Custom ascii art files must now be formatted the same as the distro ascii.
Ascii format:
```sh
"\
${c1}                 ;'-. 
`;-._        )  '---.._
>  `-.__.-'          `'.__
/_.-'-._         _,  ${c2} ^${c1} ---)
`       `'------/_.'----```
"
```
Closes #297
=> Custom ascii art: Use same format as distro ascii

neofetch
This adds Solaris detection to neofetch.
The only function I can't get is battery detection. This is caused by:
1. No laptop to test it on
2. Neither Oracle nor OpenIndiana has any documentation about it, the latest information I can get is from [2006](https://blogs.oracle.com/DanX/entry/solaris_laptop_battery_status)
(Yes, I used Arch logo because I don't know how to make ASCII logos, especially OpenIndiana.)
=> Added Solaris support

ascii/distro/pacbsd, neofetch
This commit adds support for PacBSD, a FreeBSD and Arch Linux based OS.  If you can think of a better way to do the package counts let me know and I'll be glad to change it.  The problem is PacBSD has both `pacman` and `pkg` package managers installed by default, but only `pacman` is used.  I had to do the package section the way it is because if `pkg` got called `neofetch` would hang due to `pkg` wanting user input.
This commit also lacks ASCII art because I couldn't find a good way to convert our logo to ASCII, if you have any recommendations on good tools to do so let me know and I'll gladly add it to my PR.
Signed-off-by: Adam Jimerson <vendion@gmail.com>
=> Adding PacBSD support to neofetch

neofetch
Fixes the codename when there is no point-release, and fixes Sierra support (ascii was broken)
=> fixed macOS codename function

1.8.md, README.md, config/config, neofetch, neofetch.1
Removes `stdout` mode since it's been broken for a while now and I don't see the point in fixing it.
=> Remove stdout mode

config/config, neofetch
This PR adds a new function which will be enabled by default. The function displays the product/model name of your device if it exists. For example on my laptop it shows `Lenovo YOGA 900-13ISK` and my iPhone it shows `iPhone 5s`.
Note: This feature won't work on custom built PCs or devices without OEM info.
**TODO:**
- ~~Not sure if this works on every machine yet.~~
- The file we check for the info was added in `linux 2.6.26 ~2009`<br \>
so this should be fine.
**Testing:**
If you'd like to help me test this is what you need to do:
1. Git clone neofetch.
- `git clone https://github.com/dylanaraps/neofetch`
2. cd to the new directory.
- `cd neofetch`
2. Swap to the `model` branch. 
- `git checkout model`
3. Run neofetch without a config from the directory.
- `./neofetch --config off`
4. …
=> Add new `model` function to print device model name

config/config, neofetch, neofetch.1
The reason I made this PR is simple.
Some distro's output of `lsb_release -d` is way too long. For example:
Therefore, I simplified it to only show the distributor ID and the release number
(aka. `lsb_release -sir`)
Tested on Gentoo, Fedora 24, CentOS 7, and Debian 8.5.
=> Added distro_shorthand to simplify lsb_release output

neofetch
Maybe the original committer forgot the `*` so s/he decided to get OpenBSD's case nest into the `$os` instead of `$distro`.
I suspect the original reason that because OpenBSD's `$distro` output is `OpenBSD $(uname -m)` instead of just `OpenBSD` so the results didn't appear when s/he first tested it out.
Anyway, for consistency, I decided to bring OpenBSD's battery case back to the `$distro` case and add a very little fix (which is the `*`), the problem should be fixed.
(I can't test this personally, any help would be appreciated.)
=> OpenBSD's battery status get back into the BSD case

README.md, config/config, neofetch, neofetch.1
* Added tiny option (just show the name of the distro)
* Added cases for CRUX (tested)
* Added cases for `/etc/*ease` (Tested on Debian, Void Linux, Fedora, CentOS, NixOS, and Slackware)
Question: Should we add another case for distros that uses non-standard convention (e.g. Tails, BLAG, OpenWRT)?
=> Expanded distro_shorthand to support non-LSB solutions

neofetch
`cpu_display` won't appear with `%` if `cpu_display="off"` is set. This PR fixes it.
In README.md (and in the man pages), the 4 accepted modes are `off`, `barinfo`, `infobar` and `bar`. Though I'm sure we can have a fall-back mode (which is `off`) if users don't set `cpu_display`to one of those 4 values.
=> Fixed percent not displaying in cpu_display

neofetch
The commits are for (mostly) default music players that come with DEs. Like Rhythmbox for GNOME, Banshee for Mint (Cinnamon, IIRC?), and Amarok for KDE, with the exception of deadbeef.
If I have the time (and if I figured out how the hell did Clementine break with `core dumped`) I'll expand to Clementine.
=> Added support for various music players

ascii/distro/solus, neofetch
neofetch just got shipped to Solus, and because it changed the logo not a long time ago, it would be good to update it for the relevancy.
=> Update Solus ASCII logo to a more recent one

neofetch
I actually tried this back in August, but somehow I dropped it.
Anyway, I picked this up again and decided to test around.
Bugs:
- Windows 10's `cpufreq` only has `scaling_max_freq` and `cpuinfo_max_freq`. 
- You cannot read `scaling_max_freq` (insufficient permissions), only `cpuinfo_max_freq`.
- Possible workaround: Change the default in config to `cpuinfo_max_freq`.
Other than those, it seems to work perfectly. Even in an X session.
I can only test this from a VM, so if anyone wants to test it, be my guest.
=> Initial support for Windows 10 Linux subsystem

neofetch
Neofetch will no longer clear the screen when run in `ascii` or `no image` modes. Stuff like this is now possible:
```sh
echo "Hello, bla bla"; figlet "hello, world"; neofetch --ascii
```
Bugs:
TODO: 
- Works in Travis.ci(?)
=> Don't clear the screen in 'Ascii' and 'No Image' modes. Fixes #335

README.md, neofetch, neofetch.1
This mode just displays the ascii art.
Usage:
`neofetch -L`
`neofetch -L --ascii_distro gentoo`
=> Logo mode - Only print ascii art.

.travis.yml
Travis updated the macOS build server to El Capitan, which means it has SIP now. Prefix changed to /usr/local to mitigate this
=> Fix TravisCI for macOS build

README.md
Since neofetch is now in [Gentoo's official repository](https://packages.gentoo.org/packages/app-misc/neofetch), a third party repo will not be needed anymore.
=> Changed installation instruction for Gentoo/Funtoo

README.md, config/config, neofetch, neofetch.1
Instead of using two separate functions for showing/hiding a codename/build version for Mac OS X, I decided to expand `distro_shorthand` instead to Mac OS X (and Solaris).
I can only test this for Solaris, so I need a help to test this from a Mac as well.
=> Expanded distro_shorthand to Mac OS X and Solaris

Changelog.md, README.md, config/config, neofetch, neofetch.1
This does not change any programatical references as `sw_vers` still prints `Mac OS X` in Sierra
=> change all references of Mac OS X to macOS

config/config, neofetch
- `block_width` was broken in a commit recently.
- Fixed `% s` appearing in color blocks when neofetch is run from `tty`
- `block_width` was off by one, so a value of `2` made the blocks `3` wide.
=> Fix bugs with color blocks

ascii/distro/bitrig, neofetch
Since Bitrig is an OpenBSD-based system, it should work flawlessly.
=> Added support for Bitrig

neofetch
Fixes iTunes opening if it's not running on macOS. I believe this is because of a new cache extension in Sierra, because I'm sure I fixed this bug before...
=> macOS: fix iTunes automatically opening

neofetch
This PR adds support for Windows WMs and Shells.
Supported: bugn, Windawesome, blackbox, emerge, litestep
=> wm: Add support for Windows WMs and Shells

README.md, config/config, neofetch, neofetch.1
This PR adds expands on `cpu_cores` by adding two new values, `logical` and `physical`.
Values: 
- `logical`: All virtual cores.
- `physical`: All physical cores.
Changes:
- `cpu_cores` will be set to `logical` by default.
- [macOS] Changes `hw.ncpu` to `hw.logicalcpu_max` since `hw.ncpu` is deprecated.
>HW_NCPU (DEPRECATED)
The number of cpus.  It is recommended that you use "hw.physicalcpu" "hw.physicalcpu_max"
"hw.logicalcpu" or "hw.logicalcpu_max" instead. 
[source](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/sysctlbyname.3.html)
- [macOS] Use `_max` for core output to show all cores, not just available cores.
TODO
- Support
- `physical` doesn't work on android.
Closes #379
=> Add option to hide/show hyperthreaded cpu cores.

neofetch
This PR aims to remove issues on Linux based systems where there are an endless amount of different `uptime` commands all with a different output format. Instead of using the `uptime` command we now parse `/proc/uptime` which provides us with the uptime in seconds. We then convert those seconds into days, hours and minutes.
This is how neofetch calculates uptime on macOS/BSD and this allows us to merge both functions removing ~20 lines from the script. 
Notes:
- This removes the `procps`/`procps-ng` dependency from Windows systems.
- This fixes output errors on Android.
- This allows us to add an option to enable seconds in the output. I don't know if I'll add this or not but the possibility is there.
Testing:
@iandrewt, can you test this on macOS?
=> Rewrite uptime for Linux/Windows/Solaris to match macOS/BSD

README.md, neofetch
This PR adds support for terminal emulators that don't support `\033[14t`. This escape sequence is used to get the terminal window geometry in pixels.
Those using terminals that don't support the sequence now have three alternatives to get image mode working.
- `xdotool`
- `xwininfo + xprop`
- `xwininfo + xdpyinfo`
Neofetch will detect whatever combination you have installed and use these programs to get the terminal size. 
Note: This change only affects systems running an `X server`  so macOS/iOS/Windows are excluded.
Also includes:
- w3m-img: Draw image twice
- prompt location: Take yoffset into account
Closes #382 + #385
=> Image mode: Add support for terminal emulators that don't support \033[14t

neofetch
It turns out that we were calculating used memory wrong.
Source: https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
=> Linux: Correctly calculate memory usage

neofetch
Some Solaris/illumos-based distribution used various Linux package managers such as dpkg, rpm, and portage (see more [here](http://wiki.illumos.org/display/illumos/Distributions)). It would make sense for Solaris' case to be unified with Linux.
However, Linux's `pkg` detection (I don't know which distro is that) are vastly different from Oracle Solaris/OpenIndiana's `pkg`, so a workaround (if acceptable) is used.
=> Solaris: Changed Solaris' getpackage behaviour and getdistro output

neofetch
Since DragonFlyBSD has `pciconf`, and PacBSD is basically FreeBSD + `pacman`, we can use `pciconf` for those two distros instead of relying on Xorg.
=> GPU: Used FreeBSD's method for DragonFlyBSD and PacBSD

README.md, neofetch, neofetch.1
See title.
Due to the monolithic nature of BSDs (Up until now, I still have not heard of a FreeBSD distro uses an OpenBSD/NetBSD kernel), the `uname -r` output is effectively the OS's version. Because of that, how `getkernel` works in BSDs will have to be altered significantly (meaning `kernel_shorthand` won't work in BSDs). Since the code is self-explanatory enough I won't dig deeper into this.
PacBSD and PC-BSD are exceptions. Since PacBSD and PC-BSD's `uname -s` output is `FreeBSD`, `kernel_shorthand` may be used normally.
=> Expanded distro_shorthand to *BSDs

neofetch
Without this change I get the following error when running `neofetch` after a clean install:
neofetch: line 3261: printinfo: command not found
After applying this change it works beautifully!
=> Android (Termux): Fix default config location

neofetch
[Hyper](https://github.com/zeit/hyper) is a relatively new JavaScript-based terminal that Neofetch has yet to add support for. I have added proper terminal and terminal font detection for HyperTerm running on macOS Sierra. 
[Picture](https://i.imgur.com/BHkh7J1.jpg)
There is a Ubuntu/Debian build of Hyper though, so these initial changes may need to be generalized in the future.
=> Add initial support for HyperTerm

neofetch
Made this change for these reasons:
- `[[` is bash syntax while `[` is a builtin program.
- We're already using it for regex matching `~=`.
- We can combine multiple tests like this:
```sh
if [[ "$var" == "on" && "$var2" != "off" ]]; then
```
=> General: Swap to double bracket tests everywhere

config/config, config/travis, neofetch, neofetch.1
This PR removes all vim fold marker comments that littered neofetch and stops enforcing a fold method for people editing the file. 
Instead I recommend using bash syntax folding with the following settings in your .vimrc:
```vim
filetype plugin indent on
augroup Bashfold
au!
autocmd Filetype sh let g:sh_fold_enabled=3
autocmd Filetype sh let g:is_bash=1
autocmd Filetype sh setlocal foldmethod=syntax
augroup END
syntax on
```
> autocmd Filetype sh let g:sh_fold_enabled=3
The `3` will set vim to only fold functions. Raising this number will make vim fold `if` statements and etc.
=> General: Remove all fold markers.

neofetch
This PR speeds up neofetch by only calling `uname` once instead of 4-5 times.
In this PR we assume that each flag `-s -r -m` only take up a single field each. This seems to be ok if you look at the wikipedia page for `uname` below.
https://en.wikipedia.org/wiki/Uname
=> General: Cache uname output for use later in the script

neofetch
This PR aims to fix most shellcheck errors in neofetch.
Edit: All that remains is the `find > ls` error which I'll fix at a later time since it requires a lot of testing.
There are a few shellcheck error codes that we can happily ignore since they're false positives or intended behavior. This is the command I'm currently using to test neofetch.
```sh
shellcheck -e 1090 -e 1091 -e 2034 -e 2016 -e 2009 -e 2178 -e 2128 -e 2086 -e 2153 -e 2154 -e 2068 -e 2154 -e 2153 neofetch
```
**1090**
> Shellcheck can't find the files being sourced. 
> https://github.com/koalaman/shellcheck/wiki/SC1090
This is OK to ignore.
**1091**
> Shellcheck can't find the files being sourced.
> https://github.com/koalaman/shellcheck/wiki/SC1091
This is OK to ignore.
**2034**
> foo appears unused. Verify it or export …
=> Fix all Shellcheck messages

config/config, neofetch
This PR aims to clean up the image related functions.
- Added more documentation. 
- Added `to_ascii()` and `to_off()`.
- These functions are used when falling back to different image modes.
- Renamed `$image_backend` to `$image_program`.
- Renamed `$image` to `$image_backend`.
- Renamed `$padding` to `$text_padding`.
- Renamed `$imgname` to `$img_name`.
- Renamed `$img` to `$image`.
- Renamed `check_old_flags()` to `old_flags()` to match `old_functions()`.
- Split `get_image()` into `get_term_size()`, `get_image_size()`, `get_image_program()` and `make_thumbnail()`.
- Check to see if I've missed anything.
- The only incompatibility is the renaming of `$image` to `$image_backend`.
=> Images: Rewrite image functions

neofetch
This adds support for GNOME Music and Lollypop.
My initial understanding here is in different sessions of GNOME Music, sometimes `dbus-send` produces `xesam:artist` first before `xesam:title`, sometimes it's `xesam:title` first before `xesam:artist`, resulting in this.
I wonder why don't gdbus simplify things like `qdbus` do...
NOTE: This also happened to Lollypop. So if my hypothesis is true, Spotify should be affected as well.
=> Music: Added support for various music players

neofetch
Cleanup of `get_style()`
- Renamed `$gtk2theme` to `$gtk2_theme`.
- Renamed `$gtk3theme` to `$gtk3_theme`.
- Removed arg handling from `get_style()`.
- Created new function called `trim_quotes()`
- This is now used script-wide to trim quotes.
- Created new function called `uppercase()`.
- This is now used script-wide to uppercase.
=> Style: Cleanup get_style

neofetch
At my school (and I presume many other places with strong proxies in place) the `public_ip` function returns `;; connection timed out; no servers could be reached`.
Adds a check to see if the returned text from `dig` is a comment (starts with `;`) and unsets `public_ip`
=> Fix connection timed out with public_ip (dig)

Makefile
Execution permission is not required for files under
the /usr/share/neofetch/ascii/distro directory.
Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
=> Remove execution permission flag from logo files

neofetch
This PR removes distro detection using `lsb_release`. I've made this change due to `lsb_release` reporting inaccurate distro information for some distros.
=> Distro: Remove lsb_release block

neofetch
On LFS distros, they often lack any `os-release` file, resulting in no output (often just the architecture), this adds a last fallback in case that does happen.
This mainly affects LFS distros, but since Linux and Hurd's system are similar, I'll just add another fallback for GNU Hurd distros in case someone ~~is crazy enough to~~ make GNU Hurd From Scratch.
=> Distro: Add last fallback for Linux and Hurd if no os-release was detected

neofetch
Self explanatory.
Clementine is a Qt-based music player.
Pragha is the default Music Player in openSUSE XFCE.
=> Music: Added support for Clementine and Pragha

neofetch
=> Resolution: [MacOS] If refresh rate is empty don't append Hz

neofetch, neofetch.1
This adds `cpu_temp` support for BSD distros (except NetBSD, because it already emulates Linux's CPU detection)
In FreeBSD-based systems, a kernel module (`coretemp`) must be loaded to show the temps. The warning has been added in the manpage.
=> CPU: Added cpu_temp support for BSDs

CHANGELOG.md, README.md
Although the website is haiku-os.org, the OS is named just 'Haiku' ;-)
Nice to see it supported!
=> Fix Haiku naming (it's just 'Haiku', not 'Haiku OS')

neofetch
This makes the cache function easier to use when applying it to more than one Operating System. This adds a new function called `get_cache_dir()` which sets the variable `cache_dir` according to the current Operating System.
This PR also moves the cache file check to the `info()` function directly. This means that if the cache file exists the info function isn't run at all. This change makes it so that adding caching support for all Operating Systems to an info function only takes one additional line of code. ;)
This PR also implements GPU caching for all Operating Systems and only caches the info if it's not empty.
=> General: Add cache dir var

neofetch
Yes, `GoboLinuxVersion` is correctly capitalized like that. So is `Compile`. So is `/Programs`, not `/programs`.
*Why detect `/etc/GoboLinuxVersion` instead of using `/etc/os-release`?*
Because there's no `/etc/*-release` in GoboLinux systems. But at least they have something useful in place of it, unlike GuixSD.
No logo.
=> Distro: Added support for GoboLinux

config/config
This PR changes the default image mode to ascii as it seems to be the most used mode. This should also clear up any confusion between new users.
=> Image: Change default mode to ascii

neofetch
Instead of hardcoding PacBSD and PCBSD's name, detect if `$distro` is roughly the same as `$kernel_name`.
=> Kernel: Modify how kernel_shorthand works in BSDs

neofetch
This PR stops `--ascii_colors` from coloring the text. This makes a lot more sense seeing as the flag's name is `ascii_colors`. It made no sense for it to color text in the first place. The documentation also never mentioned that `--ascii_colors` changed the text colors. 
Old behavior:
- `--ascii_colors`: Change text and ascii art colors.
- `--colors`: Change text colors. 
New behavior: 
- `--ascii_colors`: Change ascii art colors.
- `--colors`: Change text colors.
=> Ascii: --ascii_colors, don't color text colors

neofetch
When I was trying to implement package manager names I took a closer look at the packages function and noticed that we were calling `wc -l` to count the packages once per package manager. 
I started messing around with the function and came up with a way to call `wc -l` only once. We add each list of packages to an array, count the array using `wc -l` and then do some math to fix inaccuracy caused by array elements joining due to missing newlines. 
This should be way faster than the current method since we no longer pipe to an external program on a per package manager basis, we just call it once at the end. 
- Only call `wc -l` once. 
I don't have any systems with more than one package manager installed so I faked it on my machine to test locally. I'd still like someone to test this on a …
=> Packages: Call wc -l once at the end, instead of multiple times. 

neofetch
Fixes #488 
Linux Mint doesn't use the `os-release` file correctly so it's incorrectly identified as Ubuntu. `lsb_release` shows the correct information so we first check to see if `os-release` detects Ubuntu before further checking with `lsb_release`.
`lsb_release` was removed from Neofetch originally because it was causing this same issue but for some Arch based distros. Antergos was being identified as Arch because the `lsb-release` information was incorrect.
This solution hopefully satisfies both parties here.
=> Distro: Add back lsb_release detection

neofetch
Neofetch already supported showing Cinnamon version, just not for `$XDG_CURRENT_DESKTOP`. This PR enables Cinnamon version for the envar and xprop. 
Closes #494
=> DE: Print Cinnamon version, closes #494

neofetch
This updates the `lspci` `awk` command to only match `Display`, `3D` and `VGA` if there's a `"` to the left of them. This should fix issues where `Display`, `3D` and `VGA` appear in other device names. 
@konimex, can you test this on your machines? I've only got one Linux machine with integrated graphics so I'm not sure if it works with AMD/NVIDIA.
Closes #491
=> GPU: Fix bug with sound card being detected, closes #491

config/config, neofetch
This PR adds a new function called `scrot_program()` which automatically detects screenshot tools on your system. Users no longer have to specify which tool to use in their config file. 
This only supports systems with an X server, we can add support for macOS and Windows if we can figure out how to take screenshots on these machines from the commandline.
One of the tools in the `scrot_program()` function is most likely already installed so for majority of people this will be plug and play.
The `scrot_cmd` config option will still exist and still work if users want more control over which program/flags to use.
- Automatically use whatever screenshot tool is available.
- Added screenshot support to macOS
- Added screenshot support to Haiku
- This function supports every OS but Windows. …
=> Scrot: Automatically detect tools

neofetch
In some functions (such as `get_cpu` in fetching `cpu_temp`, `get_gpu`, `get_mem`, `get_battery` and `get_birthday`) it is better to use `$kernel_name` instead of `$distro` for the following reason:
Most of projects forked from the trinity (FreeBSD, OpenBSD, and NetBSD) have the same underlying `uname`, (with the exception of Bitrig and DragonFly). As we add more distros (as of now, we have 2 distros with the same `$kernel_name` as FreeBSD: PacBSD and PCBSD. But we have more cases like that, for instance, FreeNAS and pfSense), if we keep on using `$distro`, we would have to hardcode more and more of it in those cases. In such cases, using `$kernel_name` will be more effective. So, this is more like contingency in case we would have to add more detection BSD-based distros which derived …
=> BSD: Use $kernel_name instead of $distro in some functions

neofetch
Previously if the functions failed they would still be called 3-4 times. This will speed things up on systems where `get_de()`, `get_wm()` or `get_term()` failed.
=> General: Optimize usage of get_de(), get_wm() and get_term().

neofetch
We're only caching GPU on macOS systems right now so it makes no sense for Neofetch to do a file exists check for every info function and Operating System.
I'd like to revisit caching but it's going to be very difficult right now.
@iandrewt, can you test this on macOS? (Just check that GPU caching still works on macOS)
=> Cache: Simplify caching

neofetch
Simplifies the `cmus` song block and also fixes a bug where `artistsort` would appear in the output.
=> Song: [cmus] Simplify block and fix artistsort bug

neofetch
This makes `$scrot_program` an array so that we avoid word splitting and etc when we eventually call it. This also allows us to log the executable name instead of the whole command. `${scrot_program[0]}`.
=> Scrot: Use arrays for $scrot_program

neofetch
Move a lot of the tests in `main()` to other existing functions. This cleans up the `main()` function.
=> General: Cleanup main

neofetch
Battery would display as "charging" every time on the last few versions of Neofetch. This patch fixes that.
=> [macOS] Always charging bug

neofetch
This PR adds more fallbacks for Desktop Environment detection. We now also check `$DESKTOP_SESSION`, `$MATE_DESKTOP_SESSION_ID` and `$GNOME_DESKTOP_SESSION_ID`.
This should fix MATE detection issues when MATE isn't started from a Display Manager. The `xprop` fallback doesn't work for MATE so this is necessary. 
These Environment Variables were taken from `/usr/bin/xdg-open` and we should cover all bases now when it comes to DE detection.
Closes #478
=> DE: Better Desktop Environment Detection. 

neofetch
These blocks I'm removing don't actually do anything afaik, they update the `$string` variable **after** its been printed rendering it useless. `$string` isn't referenced anywhere outside `info()` and `prin()` either.
=> Info: Remove useless blocks

config/config, neofetch
This PR aims to cleanup the Linux CPU function and also fix #526.
- [Linux] Don't simplify `cpufreq` speed option names for no reason.
- ~~[Linux] Fix blank CPU name on PowerPC.~~
- [NetBSD] Remove case statement in favor of 1 line test.
- Renamed `old_flags()` --> `old_options()`.
- Update comments.
- Remove case sensitive substitutions.
- We match everything case insensitively so they were pointless.
- Simplify check for low CPU speeds.
=> CPU: Function cleanup

neofetch
This PR removes almost all of the duplication between `info()` and `prin()` by making `info()` use `prin()` to do the formatting of the output.
This PR also moves the formatting for `get_title()` to `get_title()` and the formatting for `get_underline()` to `get_underline()`. `info()` and `prin()` are now general functions with no special exceptions for functions.
=> General: Delete most of info() and instead call prin()

CHANGELOG.md, neofetch
This expands CPU name detection for Linux as per [this documentation](http://nongnu.askapache.com/proccpuinfo/cpuinfo-data-20090404.tar.bz2) to many architectures.
This should also fix #526.
=> CPU [Linux]: Added CPU name detection for more architectures

neofetch
This rewrite combines shell version detection methods.
=> Shell: Rewrite function

config/config, neofetch
- `$minutes` --> `$mins`
- This makes the variable the same length as the others.
- Moved the 3 duplicate case statements to a function. `strip_date()`
- Changed default `uptime_shorthand` value to `on`.
- `on` just makes `minutes` --> `mins` in the output.
- I've seen screenshots of people with weeks of uptime and they still have this set to `off` so the line is extremely long. This is a better default imo.
=> Uptime: Rewrite part of uptime

neofetch
- Added Haiku cores command.
- Updated Linux and macOS commands to the match the commands in the `get_cpu()` function.
=> CPU Usage: Add missing core commands and update old ones

neofetch
Title.
- Remove duplicate `dbus-send` commands.
- Remove state support.
@konimex, can you test this out?
=> Song: Cleanup get_song()

neofetch
Title.
- Fixed bug where `neofetch --config` sourced the user config twice.
- Cleaned up config arg handling.
=> Args: Fix config bug and remove large case for single regex match

neofetch
`printf` can directly declare variables. This PR removes the `$()` subshells in favor of doing it builtin.
=> General: Remove printf subshells

config/config, config/travis, neofetch, neofetch.1
This PR removes all `date` usage from Neofetch and also renames `get_birthday()` to `get_install_date()` to make things less confusing.
This adds a new function called `convert_time()` which takes the date time-stamp (eg. `2016-12-06 16:32.00000`) and converts it to (eg. `Tue 06 Dec 2016 4:58 PM`) using nothing but bash. This will allow us to use the same format for all OS since we no longer depend on `date`.
This PR also removes `$birthday_shorthand` and `$birthday_format`.
~~Note: This was more of a test to see if this was possible, it probably won't be added to master.~~
The `convert_time()` function now works with all Operating Systems and is much faster than `date`. We also don't have to deal with all of the different `date` programs and their flags. This PR will be merged once …
=> Birthday: Remove 'date' usage and calclulate date manually

neofetch
This PR aims to make the disk function as portable as possible. To make this possible we're now only displaying the information for the `/` partition. The old behavior will be re-implemented if we can figure out how to do so without issues on all versions of `df`.
Closes #542 
- Rewrote function from scratch.
- The function is `40` lines smaller than before and works on all versions of `df` \[1\]
- We only show the `root (/)` partition now.
- Removed all percentage calculation since `df` already provides us with the percentage.
- We're using the same `df` flags across all Operating Systems now. 
- No more ugly case statements or per distro hardcoding of `df` flags.
\[1\] The function doesn't work on Haiku since their `df` is wildly non-standard. (The output format and flags are 100% …
=> Disk: Rewrite get_disk()

neofetch
This PR extends our compatibility to Debian GNU/kFreeBSD.
1. Merging of GNU in `get_os()` into Linux.
As I first tested this, because the `uname` `GNU/kFreeBSD` contains `BSD`, the `$os` is set to `BSD` for the remainder of this script. So, some utilities doesn't work as a result.
Also, a GNU/kFreeBSD (and to some extents, GNU Hurd) works the same way with Linux, so it makes sense to merge them.
2. Merged Local IP of BSD (and Solaris) to Linux
It turns out that GNU/kFreeBSD doesn't have `ip` (and the Hurd one doesn't have `ifconfig`). But since Linux has both `ifconfig` and `ip`, and `ifconfig` can be used as fallback if `iproute2` somehow isn't installed, so I merged it.
3. The $PATH
Since when we interact with outside software we only require `/usr/sbin:/usr/bin:/sbin:/bin`, I've set …
=> OS: Expand support to Debian GNU/kFreeBSD

neofetch
This reverts the recent pacman fix since the user could have a non-standard path which would break Neofetch. 
Also see: #545
=> General: Revert PATH changes and add /usr/sbin and /sbin to PATH

Makefile
This removes the execute permissions when we install the config file. BASH can source scripts that aren't set as executable so this works just fine.
=> Config: Remove executable permission from config files

config/config, neofetch, neofetch.1
This PR removed `$ascii_logo_size` in place of just using `$ascii_distro`. We're already using `$ascii_distro` for `_old` and Ubuntu variants so why not also use it for `_small` variants. 
This PR also fixes all spelling errors in our docs. I noticed I spelled `variant` wrong in this PR and decided to go through the entire script with a spell checker. :P
=> Ascii: Remove ascii_logo_size

neofetch
Check if `$TERM` is `minix` before printing the escape sequences. This fixes some garbage output in minix's virtual console.
This is the only solution to this problem I've found so far.
=> General: [Minix] Fix unsupported escape sequences in Minix.

config/config, neofetch, neofetch.1
This PR makes `get_gpu()` display each GPU on a separate line on Linux systems. 
- Each GPU is printed on a separate line.
- None yet.
CC @konimex,, can you test this?
=> GPU: Print each GPU on a different line

neofetch
This PR adds song info support for Exaile.
There are also the commandline options` --get-title` and `--get-artist`, but `dbus-send` is much faster.
850ms vs 16ms on my system.
=> Add support for Exaile music player

config/config, neofetch, neofetch.1
This PR removes `$start` and `$end` and merges them into an array called `block_range`. `start` + `end` are vague and don't match the other color block options. It also doesn't make sense to split them up,
This PR also fixes a bug with `old_options()`
NOTE: This PR also adds handling in case the user's config is out of date.
=> Cols: Remove $start + $end in favor of ${block_range[@]}

neofetch
Some players report title before artist. That leads to song = titel - artist.
This PR makes sure it's always artist - title
=> Song: enforce order artist - title in get_song_dbus()

neofetch
This PR moves the PID / PPID handling from `get_term()` to two separate functions. This change was made so that we can do the same PID handling in another function. (`get_term_font`)
=> Term: Move pid handling to separate functions

CHANGELOG.md, config/config, neofetch, neofetch.1
This adds option where user can choose between using a 24-hour format or 12-hour format
=> Install Date: Add an option to use 24h or 12h in time format

neofetch
Exaile does't report artist and title if playback is stopped. That leads to `song=" -"`
Added a check to avoid printing this empty song info.
=> Song: Fix Exaile song query

neofetch
This PR speeds up song query for Pragha, Amarok and Banshee. They take half the time now. 
Most noticeable for Banshee because of it's slow query command. 
I've also changed the cmus query to avoid printing of an empty song info " - " if playback is stopped.
(Though it's only one call to `cmus-remote -Q` now, there's no significant speed increase.)
=> Speed up song query for some players

neofetch
The ultimate aim of this PR is to expand Neofetch's support to Gentoo/FreeBSD. Testing will have to be done in these distros (in an installed environment, not a LiveCD):
These testings are done because we're merging the package detection for Linux/Solaris and BSD. We all want accurate results for package, don't we?
Also, see my comments in the diff.
- Errors need to be suppressed.
- Cleanup `get_distro`, I think.
=> OS: Added support for Gentoo/FreeBSD

neofetch
On openSUSE the ASCII logo was not shown.
I hope it's the right place to fix it.
There was also a typo. `ascii_Distro="antix"`
=> Fix ASCII logo not shown on openSUSE

neofetch
Fixes bugs found in `get_de()` by @mstraube.
- Fixes `(( ))` syntax.
- Fixes `$XDG_CURRENT_DESKTOP` not being assigned properly.
- Fixes `$de == $wm` check. 
Fixes #582
=> DE: Fix bugs.

CHANGELOG.md, neofetch
In Linux and Solaris, their commands are hardcoded to use GNU coreutils, so the function cannot be shown in systems without it, like Alpine (Busybox) and Oracle Solaris (xpg4). 
This PR will change the behaviour of `install_date` overall, so it will detect which `ls` program is being used: `Busybox`, `GNU coreutils`, `xpg4` (indicated by the use of `crtime` because `--version` doesn't work), Toybox (indicated by `ACFHLRSZ` because `--version` didn't provide any indication of "Toybox") or BSD ones (fallback), instead of hardcoding them per OS.
Because I don't have a Windows (Cygwin) system, I cannot test it. As for Mac OS X, there's always Travis.
=> Install Date: Rewrite function

neofetch
On my system MATE WM Theme wasn't detected.
```
$ LANG=C gconftool-2 -g /apps/metacity/general/theme
No value set for `/apps/metacity/general/theme'
```
=> DE: Fix WM Theme not detected on MATE

neofetch
I've rewritten the font detection for Konsole. It now
- works for `org.kde.konsole` and `org.kde-konsole-$PPID`
- works if the profile filename differs from the profile name
- doesn't use hardcoded config file paths
- works for KDE5 and KDE4
Tested on Arch, Kubuntu, openSUSE, Slackware, KDE neon.
Note:
With Konsole versions affected by https://bugs.kde.org/show_bug.cgi?id=358083 (I think..)
it's possible that we have two profile files containing the same profile name.
I noticed this behavior (with a new created user) on Kubuntu 16.04:
Starting Konsole -> edit current profile -> close konsole -> restart it -> edit current profile
Produced two differnt profile files with the same profile name in it.
That's the only situation I was able to produce two different profile files containing the …
=> Term: Rewrite Konsole font detection, closes #576

neofetch
- Remove unnecessary quoting and variable assignment checks.
- We don't need to check to see if the var is empty in arithmetic tests.
- `$` and `${}` aren't needed/
- Removed unnecessary quoting to match other existing syntax.
- Fixed typo in GNOME section of `get_wallpaper()`.
=> General: Fixes

neofetch
`readarray` works better here since it ignores `IFS` and splits elements by newline.
@konimex, can you test this on your multi GPU system?
=> GPU: Use readarray instead of modifying IFS

neofetch
- Adds support for Yarock and Qmmp.
- Generally don't print empty song info `" - "`.
This way we don't have to care about that for every single player.
=> Song: Add support for Yarock and Qmmp

neofetch
This adds detection for any Windows systems using [MSYS2](https://msys2.github.io/) as opposed to Cygwin.
The changes are mostly compatibility changes because apparently MSYS2/MinGW's `wmic` doesn't support `/value`.
=> OS: Added support for Windows (MSYS2)

config/config, neofetch, neofetch.1
This PR adds a new option called `disk_show` which allows you to specify which disks you want to display in the info. (one per line).
- Display multiple disks (one per line).
- Subtitle is updated to display mount point `Disk (/)`, `Disk (/mnt/Local Disk)`.
- The subtitle currently shows mount point, should we instead display the drive name? `/dev/sdXX` 
```sh
Disk (/mnt/Videos): 24G / 60G (45%)
Disk (/dev/sdc1): 24G / 60G (45%)
```
- Broken in travis.
```sh
neofetch --disk_show '/' '/dev/sdc1' '/mnt/Videos'
disk_show=('/' '/dev/sdc1' '/mnt/Videos')
```
=> Disk: Add option to specify which disks to show

neofetch
This should fix #608 
Works for me wether the `[hints]` section is above or below the `[options]` section. With and without commented `font=` in the `[hints]` section.
=> Term: Fix termite font detection, closes #608

neofetch
Adds font detection for Pantheon Terminal.
Tested on Arch and Elementary OS.
=> Term Font: Add support for Pantheon Terminal

neofetch
Change `XFCE` in output to `Xfce`, as per Xfce branding: https://www.xfce.org/about
=> XFCE -> Xfce

neofetch
Neofetch now understands relative paths when specifying image files, ascii files and directories.
For example:
```sh
neofetch --w3m ~/Pictures/Wallpapers/10.jpg
neofetch --w3m ~/Pictures/Wallpapers/
cd Pictures
neofetch --w3m Wallpapers/10.jpg
neofetch --w3m Wallpapers/
cd Wallpapers
neofetch --w3m 10.jpg
neofetch --w3m .
cd ..
neofetch --w3m ../test.png
neofetch --w3m ../
```
=> General: Neofetch now understands relative paths

neofetch
[Before](https://i.imgur.com/YlZ7Fcu.jpg)
[After](https://i.imgur.com/qOmRdsG.jpg)
Linebreaks in the config file caused stray spaces to print over the image in Iterm2 on macOS Sierra.
=> Image: Fixed issue where linebreaks printed stray spaces over the image

neofetch
Well, if i remember correctly this issue was here in the past and now is present again.
What if i'm using mpc on my computer, to control mopidy on rpi? This commit is fixing this issue, maybe it's not good optimized, i've done my best i think. Simply neofetch doesn't display SONG when it doesn't find any player on host.
This screenshot shows output of command used to determine which player is currently opened on host.
=> MPD server on another host

neofetch
- Fix typo in comparsion
- Use `get_song_dbus` for audacious since audtool returns `Artist - Album - Title`
- Don't print if `$song` is emtpy and `song_shorthand` is on (#638)
=> Fix song_shorthand, use dbus for audacious

neofetch
Adds support for `neofetch` when installed on Haiku with `PREFIX=/boot/home/config/non-packaged make install` (as is convention)
`neofetch` now properly loads ASCII art and default configs when installed "properly" on Haiku (without being packaged).
Would probably be better to have a `$PREFIX` variable defined somewhere, to be pre-populated by running `PREFIX=/foo/bar/baz make install`.  Not entirely sure how feasible or desirable that would be versus this sort of one-off case.
See "Issues".
=> Fix paths for "proper" Haiku installation

neofetch
This PR shows `MiB` on systems that output memory in Mebibytes and `MB` on systems that output memory in Megabytes.
Closes #644 
@konimex, are you happy with this change? All OS print the output in Mebibytes apart from `AIX` which displays the output as Megabytes.
AIX `svmon` manpage: https://www.ibm.com/support/knowledgecenter/ssw_aix_61/com.ibm.aix.cmds5/svmon.htm
=> Memory: Change label to MiB from MB

neofetch
The default configuration of Alacritty happens to include a comment, so
the output is the following:
> Terminal Font: monospace # should be "Menlo" or something on macOS.
This pull request fixes this and the output is as expected:
> Terminal Font: monospace
=> Fix Alacritty font detection

neofetch
This PR adds support for the [Spectacle](https://github.com/eczarny/spectacle) window manager.
If Spectacle and Kwm are both running, Kwm pretty much overtakes everything and Spectacle does nothing, which is why detection for it happens beforehand.
=> WM: Add support for Spectacle on macOS

neofetch
This PR outputs the font of the currently active profile of iTerm2. I have written this in the last couple of weeks for a debugging script in [powerlevel9k](https://github.com/bhilburn/powerlevel9k) (debugging script not yet online) when I discovered #664 , so I wanted to contribute it back to here..
This is a different approach than @jorgegonzales uses in #668 (sorry). And sorry @jorgegonzales for entering the discussion so late..
This fixes #664
1. We ask iTerm2 via `osascript` to tell us the currently active [profile name](http://www.iterm2.com/documentation-scripting.html)
2. We loop over all profiles
3. If there is a profile with the same name found, then we parse the relevant information via `PlistBuddy`
It does **not** work when
- iTerm2s [dynamic …
=> Add iterm2 font detection

neofetch
This PR adds detection for [Amethyst](https://github.com/ianyh/Amethyst).
Due to their incompatible behaviors, we will default to Amethyst if Spectacle is running, and then to Kwm.
=> WM: Add support for Amethyst on macOS

config/config, neofetch
This PR makes `-s`/`--scrot` easier to use and removes the configuration needed before it would work. (Creating `~/Pictures`). 
- `neofetch -s` will save a file in the current directory named: `neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png`
- `neofetch -s test.png` will save a file in the current directory called `test.png`
- `neofetch -s ~/` will save a file in `~` called `neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png`
- `neofetch -s ~/test.png` will save a file in `~` called `test.png`.
Note: 
- The value of `scrot_dir` is ignored now.
- `-v` now shows where the screenshot was saved.
This closes #680.
=> Scrot: Make scrot easier to use.

config/config, neofetch
Adds a new, disabled by default info function to display the system locale. The output is just the value of `$LANG` and is set to `C` if empty.
Output: `Locale: en_US.UTF-8`
Closes: #679
=> Info: Added function to display locale.

neofetch
This PR adds battery support for devices that use `axp288_fuel_gauge` for the info.
Some (not sure if all) Bay Trail Laptops/Tablets for example.
Note:
The Linux battery support for Bay Trail devices wasn't so good up to kernel 4.10. 
On my Laptop it started working with 4.11-rc1. I think..
=> Add battery support for Bay Trail devices

neofetch
This commit makes the `--ascii_distro Ubuntu-Studio` option display the Ubuntu Studio logo.
The `ascii/distro` directory has an `ubuntu-studio` file, and Ubuntu-Studio is documented as an option for `--ascii_distro` in the `--help` text. Previously when I used that option, it fell back to the default Ubuntu logo.
This change adds a case for Ubuntu-Studio to set `ascii_file` and the colors.
=> Fix --ascii_distro ubuntu-studio

neofetch
Tested on Arch Linux.
Notes:
Without the added space in the `awk` command Tomah<b>awk</b> won't be detected.
=> Song: Add support for Deepin Music and Tomahawk

neofetch
Add support for distros installed via crouton on Chrome OS
=> OS: add Chrome OS crouton support

neofetch
Each config parameter is allowed arbitrary whitespace before it.
It took me a long time to work out why it was always returning the /etc/xdg/termite/config value!
=> Fix termite font matching

neofetch
This "absurdly long" command to get player is returning this on my ubuntu installation:
```sh
/usr/bin/ibus-daemon --daemonize
```
Then this after first addition (ibus) to awk
```sh
indicator-mpd
```
After this commit, player is being detected properly. In my case - spotify
=> Do not detect ibus* or indicator* as player

neofetch
A lot of OS are *NIX, and as such, will use X (unless there are some arcane new method, aside from Wayland which only supports Linux and FreeBSD atm) for graphical environment.
It would be easier to maintain those functions as we don't have to add every OS to the cases.
=> Misc: Use fallback values for some functions

neofetch
I found a way to do font detection for MATE Terminal.
It requires to create a temporarily file. I decided to use the `/tmp` directory, but I'm not sure if it will be available (and writable)  on all systems?
=> Term: Add font support for mate-terminal

neofetch
Just an extra possible directory to search for w3m-img before outputting that it wasn't found on the system.
It fixes my issue of being unable to output images with neofetch when using it on FreeBSD 12-CURRENT.
=> Patch to make w3m image backend work on FreeBSD 12

neofetch
This PR adds support for detecting if the macOS is running on a PC (Hackintosh)
Since FakeSMC.kext is a mandatory kernel extension for Hackintosh to boot, this PR checks if FakeSMC is loaded.
More about Hackintosh: [Wikipedia: OSx86](https://en.wikipedia.org/wiki/OSx86)
- Detect if the current macOS is a Hackintosh
Maybe text rearrangement? "Model" line is a little bit too long (though still less than 80 chars)
=> Model: Add support for Hackintosh

CHANGELOG.md, neofetch
Self-explanatory. Closes #731.
Further testing. I've only done two tests in my own environment using a free shell service and a VM.
=> Terminal: Disable terminal detection if device is connected over SSH

neofetch
In FreeBSD's detection, we use `top`. Since the output is highly dynamic, if we use the `awk` command, often times the line we look for will land in `$4` instead of `$5`.
This reduces our dependency on `top`, and as a result, more accurate memory.
Source: https://www.cyberciti.biz/faq/freebsd-command-to-get-ram-information/
=> Memory [FreeBSD]: Fix inaccurate free memory calculation

CHANGELOG.md, neofetch
In systems like Solaris and AIX, often times the `$machine_arch` output is *not* the actual machine architecture, but the machine ID/machine name. This is especially true in [the manpage for uname(1) for AIX](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds5/uname.htm):
```
-m     Displays the machine ID number of the hardware running the system.
```
and if we want to detect proper machine architecture,
```
-p 	Displays the architecture of the system processor.
```
in Linux, however, if we use `-p`, the output will be `unknown`, more testing is needed. I'll merge this when it's ready.
=> Distro: Refactor $machine_arch

neofetch
Add support for Neovim `:terminal` mode, the embedded terminal emulator in neovim.
- Showing **Neovim Terminal** if neofetch is running under neovim terminal emulator and
- Showing **VimR Terminal** if neofetch is running under neovim with VimR.
=> Terminal: add support for Neovim terminal emulator

CHANGELOG.md, neofetch
On systems with system-on-a-chip like Raspberry Pi or Android phones, their CPU output in `model name`/`Processor` is `ARMv6-compatible processor rev 7` instead of whatever supposed to be there. They are placed in `Hardware` instead.
```
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 2.28
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7
Hardware	: BCM2708
Revision	: 0004
Serial		: 00000000163b89e4
```
However there are systems like this, which put proper name of Processors in `Processor` and put the hardware model in `Hardware`.
```
Processor       : StrongARM-1110 rev 9 (v4l)
BogoMIPS        : 137.21
Features        : swp half 26bit fastmult
CPU implementor : 0x69 …
```
=> CPU [Linux]: Fix inaccurate ARM CPU on SoC systems

neofetch
`prtconf` can be *really* slow in AIX (the total output is 8 seconds for neofetch for a full output), so to ease the burden, some commands are changed so the output will be faster.
<s>The `-M` option exists in default AIX uname, but when there's GNU uname, the option `-M` doesn't exist. We can put add standard PATH for neofetch and add the `PATH` before it so it will be like this:
`export PATH="/usr/xpg4/bin:/usr/sbin:/sbin:/usr/etc:/usr/bin:/bin:${PATH}"`</s>
---------
P.S.: I set up a crontab in an AIX server that should generate output [here](http://polarhome.com:773/~koni/output) and logs [here](http://polarhome.com:773/~koni/log) from neofetch's latest master. So if something is up with AIX we can fix them.
=> AIX: Reduce dependency on prtconf

.travis.yml, config/config.conf, config/travis.conf, neofetch
Closes #762 
@konimex, you'll have to update #754 to add the `.conf` extension. 
Also I'm not sure about how we're going to handle existing people's configs, do we accept both formats?
=> config: Add .conf extensionn, remove shebang.

CHANGELOG.md, config/config.conf, neofetch, neofetch.1
`speed_shorthand` will have to be disabled for CPU speed below 1 GHz. Unless we want to nest another `if` there.
=> CPU: Fix inaccurate speed for processors below 1GHz

neofetch
Currently it looks like this:
Added `-len 100` because otherwise that call to `xprop` is very slow.
(the property _WINDOWMAKER_ICON_TILE is very long)
=> WM: Fix/add Window Maker detection

neofetch
I hope this PR is not too big. :)
It does the following:
- Song support for Pogo
- Font support for LXTerminal
- Font detection for xfce4-terminal was wrong when it is configured to use the system-wide font
- Remove one awk command from the font detection of HyperTerm
- Exit awk early when the font name was found (sakura)
=> Various additions and enhancements

neofetch
This is mostly done so if `cpu_speed` is disabled, `cpu_temp` will still be shown.
=> CPU: Add CPU temp separately instead of embedding them in speed

neofetch
In maximzed windows and fullscreen mode font detection for MATE Terminal did not work.
The grep commands failed because the config file contains extra lines if the window is maximized and/or fullscreen.
- Fixes font detection when maximized or fullscreen
- Faster (nearly 2 times)
=> Term: Fix mate-terminal font when maximized or fullscreen

neofetch
If a user has maim(1) installed as well as scrot(1), they likely wish to use the former instead of the latter, as it is less commonly installed (and is even described as "supposed to be an improved scrot").
=> Prioritise maim(1) over scrot(1).

neofetch
Ignore terminal emulators detected as `kdeinit*`.
=> Term: get_term(): ignore kdeinit, #791

neofetch
Fixes #702 
Ideally we don't want to pipe a second time but it doesn't seem like there's another way of doing this. (Unless `awk` has a way of removing duplicates?) Also it'd be nice to append a count to the end but I don't think it's possible with the way the function is written. We'd have to rewrite it so we'll save that for another day.
I've tested this on an AMD and Intel machine but it should work on all others as well.
=> gpu: Hide duplicate identical gpus

neofetch
Very specific case, but for example having Unifont (xft:Unifont:style=Medium:antialias=false") as your terminal font, makes Neofetch print it as "Terminal Font: style=Medium:antialias=false" instead of "Terminal Font: Unifont".
This is due to the fact, that it looks for "font:" string. Fixed it by making it look for "*font:" instead, but I'm not sure if that's the right approach.
Pictures say more than words :smiley:
=> Fix Terminal Font displaying incorrect information in urxvt, if one of the fonts has 'font' in its name

ascii/distro/siduction, neofetch
This pull-request adds support for the [Siduction](https://siduction.org) GNU/Linux Distribution.
It's not the prettiest ascii logo, but it does the job :smile:.
=> OS: Add support for the Siduction OS

neofetch
It does not work with the linebreak and still fits in line length 100 without it.
=> Term: Fix mate-terminal font

neofetch
- Show GTK info when running KDE.
- Fixed bug in `get_wm_theme` for KDE systems.
Closes #808
=> theme: Show KDE and GTK output if both are available.

neofetch
On some devices I tested (Fujitsu Lifebook E754, ThinkPad T410s, ThinkPad T400), the battery gets assigned the device path /sys/class/power_supply/CMB1 when using Fedora 26 with Kernel 4.12.5-300.fc26.x86_64. I adapted the get_battery function for this case.
* Fix get_battery for Fedora 26
=> fixed get_battery for device names starting with CMB

config/config.conf, config/travis.conf, neofetch
Adds a new (*`off` by default*) info function to display the GPU driver. **This currently only works on Linux.** This works by checking which kernel driver the GPU is using.
I'm not sure if adding support for other OS is nessecary as most OS only have one driver per GPU vendor or the OS is used only on mainframes/servers which have no GPU.
(*This will be merged for Linux users regardless though.*)
Closes #766
=> info: Add support for GPU Driver [Linux]

neofetch
Adds support for the new/upcoming KDE music player `Elisa`.
Tested with `elisa-git` from AUR.
=> Song: Add support for Elisa

neofetch
Fix displayed font when using KDE. See #821
before
`Font: Noto Sans,10,-1,5,50,0,0,0,0,0,Regular [KDE], Noto Sans Regular 10 [GTK2/3]`
after
`Font: Noto Sans Regular 10 [KDE], Noto Sans Regular 10 [GTK2/3]`
=> Font: Fix KDE font, #821

neofetch
the grep command which included `[c]hunkwm` in it's search parameters was triggering the `*"kwm"*)` glob in the switch statement, since the **kwm** substring of [c]hun**kwm** fits the glob pattern, if that makes any sense....
This was the most obvious and simplest fix I could come up with
=> tiny fix for WM always being detected as Kwm on macOS

neofetch
The Install Date function used to print a seemingly random date, I think it might have been the time last booted? Or at least it was when `/var/log/install.log` was last modified. I've fixed it so now it's based off of the creation date of that file. I'm not sure if other OSes that error on `ls --version` support the method I used (just adding `-u` to the ls command for macOS only), and its probably file system specific, so I made the change only work on macOS.
=> Fix Install Date for macOS

config/config.conf, neofetch
Adds `gpu_driver` support for macOS, really only affects Mac Pro and Hackintosh systems (although I think some older iMacs and MacBook Pros may have this work too). Only works for Nvidia cards with the Nvidia web drivers installed, otherwise it just falls back to "macOS Default Graphics Driver" (which is what the Nvidia web drivers refer to the included driver as, so I'm referring to the default driver for all GPUs as that)
=> gpu_driver: Add macOS (Nvidia) support

neofetch
'blocks' keyword is also present in busybox' df.
Busybox' df also has -P and -h flags, so it can be detected as normal df.
'Tracker' keyword seems to be exclusive to Haiku's df.
Tested on Alpine with busybox and on Haiku.
=> disk: change Haiku's df detection

neofetch
in mac, iterm2 cannot process ${image//'/'//_}, therefore make_thumbnail() will fail and there will be no image displayed.
=> fix in mac can not make_thumbnail

neofetch
Specific support for detecting tcsh is needed as versions < 6.11.04 do not implement the --version flag. The only way to reliably get tcsh version regardless of release is to check the $tcsh variable
Also works when tcsh is emulating csh(getting the version of the original BSD csh is trickier though afaik)
=> Shells: add support for tcsh

neofetch
neofetch currently only works on 64-bit installations of IRIX, change so that it matches on the uname output from 32-bit too. Works on my O2.
=> OS: detect 32-bit IRIX

neofetch
I was surprised that OpenWrt and LEDE are detected as generic Linux. Didn't noticed it or something. After this commit it's fine.
=> distro: fix OpenWrt/LEDE detection

neofetch
This fixes the CPU temperature and memory used values in OpenBSD.
For the memory usage, the script was previously looking at the wrong vmstat field, and was dividing by 1024, even though the value was already in MiB.
For the CPU temperature, the sysctl call was only looking for lm0.temp0, which doesn't exist on some machines.  I changed it to look for cpu0.temp0 as well.  I also changed it to remove the second 0 after the decimal, which was previously making the temperature formatting logic produce an incorrect value, as it was only expecting one 0 after the decimal.
I also changed the only line that was using a tab as indentation to the appropriate 4 spaces per indent level format.
Before:
```
./neofetch --cpu_temp C
_    rage311@x240-openbsd
(_)   ----------------------------------- 
| …
```
=> Fixes for OpenBSD CPU temperature and memory used values

neofetch
Fixes #902 as well as makes a few fixes/tweaks for macOS; tested on 10.12.6
* Feature detection on macOS that relies on AppleScript snippets works again (#902)
* Music player detection on macOS is now more reliable at detecting iTunes vs. Spotify — no guarantees made if both are running (looks like it prefers iTunes on my machine)
* Now detects Light vs. Dark theme in addition to Blue vs. Graphite, outputting `WM Theme: Blue (Light)` (for example)
* neofetch's `uppercase()` function no longer prevents feature detection under `bash` < v4
* Music player detection is still not perfect — ideally it would use fancier regex to ignore the iTunes Helper and Spotify daemons, but then the `grep` would match itself, so that would have to be handled as a failure to match any player.  This shouldn't …
=> macOS fixes & improvements

ascii/distro/hyperbola, neofetch
=> OS: Add support for Hyperbola GNU/Linux-libre

neofetch
Added support for pulling font details when using kitty terminal on macOS, and perhaps *nix.  (Have not testet the latter.)
Please review.  Were a bit unsure how to format the line breaks.
* Show font details when using the kitty terminal.
=> Added font support for kitty terminal

neofetch
Description: Add a os-release check to make sure the distro really is Arch Linux when `pacman` is in the $PATH
------
Reason: Before this same bug was solved by removing /usr/games from the $PATH. However this did not work for 2 reasons:
1. The pacman game could be somewhere else, (OpenBSD for example has /games, /usr/games, and /usr/local/games
2. It could be anything! Such as this color script in my ~/bin/ascii folder:
=> fix pacman name conflict bug

neofetch
This fixes a small bug in the regex used for retrieving the font size used in the kitty terminal.
The regex used is too greedy so matches the `map ctrl+shift+backspace restore_font_size` found in my config.
The proposed fix should match any preceding whitespace (before `font_size`) and require at least one whitespace character after `font_size` (so that we don't match too much).
=> Fix kitty font_size regex

.travis.yml, CHANGELOG.md, neofetch
Self-explanatory. Closes #933.
Interestingly enough, this only happens in UNIX-certified systems (macOS, AIX, Solaris), but not Linux (including Android/Termux) and BSDs.
The most obvious one is this commit will trigger [SC1117](https://github.com/koalaman/shellcheck/wiki/SC1117). We'd have to exclude it, or change the double quotes to a single quote.
Testing
=> Misc: change all escape sequences from \\e to \e

neofetch
This adds font detection for the suckless terminal (st).
Command line arguments are checked first, if a font is not specified via command line arguments we run `strings` on the `st` binary and `grep` for something that looks like a font. In my testing this has worked well except in the following edge case:
**config.h**:
```h
static char font[] = "Liberation Mono";
```
The above is technically a valid font. As it doesn't contain anything that indicates it's a font declaration e.g "pixelsize=", "size=", etc it will not be matched.
Other than this one edge-case, in my testing the font has matched correctly 100% of the time. However, it's possible that some patches a user might have applied to `st` (or any modifications that a user has made) might cause `neofetch` to match the wrong thing. …
=> Font detection for suckless terminal (st)

neofetch
This PR removes unsafe word splitting from two commands related to AIX and IRIX.
I can't test these changes so this won't be merged until someone can let me know that they don't break neofetch.
=> general: Remove unsafe splitting.

neofetch
Adds fetching wallpaper set with [`setroot`](https://github.com/ttzhou/setroot).
I added it with higher priority than `feh`, since it can be used only as wallpaper setter, while `feh` could still be used as image viewer. ~~even tho there is probably zero overlap between users.~~
=> Add 'setroot' wallpaper fetching

neofetch
Hi there,
Just a little PR to add support for temperature monitoring on AMD Zen processors using the k10temp module.
Please let me know if this is the correct way to go about implementing it. This was tested on a Ryzen 5 1600 on Arch Linux.
This adds support for Zen based processors(AMD family 17h) like the Ryzen series using the k10temp module.
This requires either having a patched kernel with the hwmon updates see - lkml.org/lkml/2017/9/6/684
Or kernel 4.15+ where the patch was merged.
Adds temperature monitoring support for AMD Zen based processors
=> cpu_temp: Add support for Zen processors

neofetch
XDG_CURRENT_DESKTOP in Ubuntu 18.04 with Unity is containing some extra info.
Before patch:
After:
=> de: fix Unity in 18.04

config/config.conf, neofetch, neofetch.1
The goal of this feature is to be as generic as possible. We call `$wm` with `--version` and `-v` and use whatever exits with `0`.
This will stay `off` by default.
Closes #918
=> wm: Added WM version.

neofetch
Initial take on a fix for the regex bug.  The old regex included the new line above, making it hard to extract the right portions I believe.  This worked on macOS.  Not sure with `gawk`.
Old regex resulting in adding the line above.  To me giving a blank output:
Please take a look.  I hope I am on the right right, spent almost 5-7 hours trying to learn regex 👍 
Trying to fix regex that broke kitty's font size reporting. PR https://github.com/dylanaraps/neofetch/pull/935
```ini
font_family          Hack Nerd Font Mono
font_size            13
scrollback_lines     20000
window_padding_width 5
foreground           #fce8c3
background           #1c1b19
cursor               #fce8c3
color0               #1C1B19
color8               #2D2C29
color1               #EF2F27
color9               #F75341 …
```
=> tweak kitty font regex

neofetch
fallback to get_song_dbus() when song_shorthand is on
audtool won't work due to the `-` separator in it's output
=> song: fix audacious album

neofetch
Fixing my own regression in https://github.com/dylanaraps/neofetch/pull/973.
I seem to have escaped the carrot for the begging-of-the-line, and I also added the same check to `font_family`.  I had lines commented out and they were picked up by the regex.
Sorry for the regression.
=> kitty: fix regression in regex

neofetch
Get rid of a `awk` call in `get_song_dbus()`.
Test with all players that use `get_song_dbus`.
=> song: simplify get_song_dbus

neofetch
The mpris player name has changed.
```
$ qdbus | grep mpris
org.mpris.MediaPlayer2.DeepinMusic
```
```
$ deepin-music --version
deepin-music 3.1
```
=> song: fix deepin-music

neofetch
Add song support for vlc.
Does not work with current `get_song_dbus()`.
Needs #983 to be merged.
=> song: add support for vlc

neofetch
Add wm_version support for xfwm4.
This is the output of `xfwm4 --version` on my system.
```
This is xfwm4 version 4.12.4 (revision 7844952) for Xfce 4.12
Released under the terms of the GNU General Public License.
Compiled against GTK+-2.24.31, using GTK+-2.24.32.
Build configuration and supported features:
- Startup notification support:                 Yes
- XSync support:                                Yes
- Render support:                               Yes
- Xrandr support:                               Yes
- Embedded compositor:                          Yes
- KDE systray proxy (deprecated):               No
```
=> wm_version: add support for xfwm4

neofetch
Figure out the GPU brand and append it to the start of the GPU string.
This needs testing as it my duplicate the branding.
Closes #959
=> gpu: Fix ATI/AMD branding issue.

neofetch
This fixes cases where `ItunesHelper` is running but `Itunes` is not causing an incorrect match. This needs testing as the output of `ps -e` may differ on different machines.
=> song: Fix matching

neofetch
Pragha supports mpris2.
Simplify song function by using `get_song_dbus`.
=> song: use get_song_dbus for pragha

neofetch
Amarok supports mpris2 so we can use `get_song_dbus`.
Exaile 4.0.0 will also support mpris2, added a reminder for now.
=> song: use get_song_dbus for amarok

neofetch
This commit adds support for:
- `hw.sensors.acpibat0.amphour[03]` for battery charge statistics. OpenBSD's `acpibat(4)` uses either this or `hw.sensors.acpibat0.watthour[03]` kernel states, so on some laptops Neofetch wasn't able to get the battery charge percentage. 
- Charging status
It passes shellcheck and i tried to stick to CONTRIBUTING the best i could.
=> battery/OpenBSD: improved charge%, adds status

neofetch
`"$SHELL" -c "printf %s \$KSH_VERSION"` as part of the shell version
detection for ksh and mksh was expanding to `printf %s $KSH_VERSION`
inside of shell. This resulted in `$KSH_VERSION` being substituted as
multiple arguments to printf. While (afaik) unspecified, mksh, bash
and zsh resort to repeating the format strings. This resulted in all
spaces missing from `$shell`, which in turn caused the string cleanup
to fail: `Shell: mksh @MIRBSDKSHR562017/08/29`
Quoting `$KSH_VERSION` causes it to be given to printf as a single
argument, which preserves its spaces. The output after this change
looks like follows: `Shell: mksh R56 2017/08/29`
=> Fix borked version display for mksh

neofetch
Yakuake terminal uses the same config files as Konsole.
=> add term-font support for yakuake

neofetch
reset the color after drawing the ascii logo.
should fix #1065 and similar issues. This was probably not noticed before because ascii-drawing is the first called function and many other after it do reset the color.
Note: line_break() also does not reset the color, but I think that's fine, since it does not use color.
=> add color-reset to ascii logo drawing

neofetch
Fix a bug caused by not correctly unset IFS to read array.
Image cannot correctly display due to get_window_size() cannot get window size. Tests passed on MacOS High Sierra.
For the issue: [Images not displaying #1045](https://github.com/dylanaraps/neofetch/issues/1045 "Images not displaying")
=> Fix cannot correctly get window size

neofetch
Hi,
(edited to reflect further changes) 
What's new in that set of commits: 
- get_disk
-  On OpenBSD you can't use `df` against a `/dev/...` unless being root or in the 'operator' group. A separate disks array creation using `awk` has been introduced only for this OS.
- get_wm
- `ps -e` for non-EWMH WM won't work in OpenBSD. So i introduced a `ps_flags` array the same way we do for disks.  
- added fvwm support
- get_model
- Adds vmm(4) (OpenBSD's hypervisor) support
These changes impacts all OSes, so i've cross tested on Debian GNU/Linux, and it was OK. It should be the last PR for now, since i reviewed everything else and it works.
=> Several OpenBSD related fixes

neofetch
Kitty recently updated and broke just using "kitty icat <image>" however, "kitty +kitten icat <image>" still works as intended.
This commit makes the neofetch script use +kitten.
=> Updated to fix new kitty bug prior to kitty fixes

neofetch
Neofetch error, doesnt show ASCII image in tty(text mode) while used an image.
Displaying alternative Distros ASCII Logo in GNU/Linux text mode.
ASCII Logo doesnt display automaticly in text mode.
=> get_ascii: Do not parse file if it's an image file

neofetch
The kitty image backend was merged in #953 and v4.0.0, but the comment hasn't been updated to reflect the new backend being a valid option. This is important so that people can stumble upon this while editing their config, and so that people know it's a valid option. :slightly_smiling_face:
=> Update config comment with kitty backend.

neofetch
Resolves the annoying edge case in the awk statement. Also, I've found this isn't necessary on Mojave anymore, iTunesHelper hasn't been run since upgrading for me
Closes #1059
=> get_song: stop iTunesHelper from being detected

neofetch
Fixes the match for `active`, also changed `wired` and `occupied` to have the leading space to be safe.
Closes #1047
=> get_memory: fix awk for vm_stat on macOS

neofetch
Lubuntu changed from LXDE to LXQt with the current release (Lubuntu 18.10), and changed their logo accordingly.
=> new logo for Lubuntu

neofetch
Awk has built-in functionality to separate output fields. So why not use it? :wink:
=> Misc: Use comma syntax in awk to print spaces

neofetch
Fix some issues in get_song().
- Use `get_song_dbus` for rhythmbox. Partial fix for #1102 
- <del>Fix matching in `get_song_dbus`. With rhythmbox `AlbumArtist` was printed instead of `Album`. 
The issue was already discovered by @xPMo, see #1090</del>
- include PR #1090
- Fix detection of elisa player.
=> Song fixes

neofetch
- Adds support for the scoop package manager in Windows
Resolves #1129 
If using `tot scoop list` in the environment that Scoop installs neofetch to, bash throws the error `bash: /dev/fd/62: No such file or directory`.
Since this is the environment most likely to be reporting Scoop packages with neofetch, the `dir` function was used instead.
=> Adds scoop package manager support

neofetch
- Show `Unknown Artist/Title/Album` in output if a tag is unavailable.
- Fix issues with non-english song tags.
- Removed Google Play support (tool that neofetch uses is unmaintained and doesn't work anymore.)
- Fixed issues with `qmmp` and `deadbeef`.
- Added config option to show music player in output.
=> song: Fix various issues

neofetch, neofetch.1
Also adds 'tiny' to manpage where flags support it.
=> Where supported, keep on/tiny/off flags in the same order

neofetch
The variables blocks, blocks2, and cols were not set as local in the get_cols function, which made neofetch print whatever value they had before showing the colorblocks. This commit makes these variables local so the output doesn't get affected if they are set (e.g. export blocks="string") beforehand.
=> Made variables local in get_cols function

neofetch
Self-explanatory
With #1170 in mind, I decided to change AIX's `get_memory` method a little bit. This allows us to use `MiB` universally and not having one OS stuck with `MB` (although I think AIX interprets `MiB` and `MB` as the same).
N/A, tested on AIX 7.1
=> Memory [AIX]: Detect memory based on pages (like Solaris)

neofetch
In the newer ARM devices (say, Android devices, Raspberry Pi, etc.) it seems the `Processor/model name:` field [isn't used at all](https://github.com/pytorch/cpuinfo/commit/3365a916ae9cbd5d4e00af3c70c97a8033f4a2c5).
In old ARM devices (aka. [Intel StrongARM](https://github.com/randombit/cpuinfo/commit/d66ca6699880723efff6e22afe36a7364545376e/arm/arm.004)), this was filled properly, but with the future of ARM (especially in the age of SoC), I doubt ARM manufacturers will fill the field properly again (apart of generic ARMv7 processor rev 8 or something like that).
=> CPU [Linux/ARM]: Use Hardware field directly

neofetch
I've got a shortcut defined in kitty to change the font size. The relevant part of 'kitty --debug-config':
```
Changed shortcuts:
shift+control+minus KeyAction(func='decrease_font_size', args=())
```
My neofetch output:
```
Terminal Font: Hack ', args=())
```
This commit changes the parsing to an awk pattern that only matches the start of lines in the debug output.
New output:
```
Terminal Font: Hack 8.9 
```
=> Robuster kitty font parsing

neofetch
Fixes the output of WM Theme from always showing Blue
Resolves #1130 
Support for all 8 colour options, and light/dark mode
Probably doesn't work on older versions of macOS anymore?
=> WM Theme: update for Mojave

neofetch
A [recent commit](https://github.com/dylanaraps/neofetch/commit/60d3aa3f10f8f17ef25d2adab91cb60f5cc65a49) simplified the CPU name fetch. However, in ARM platforms it returns now a too generic name. The proposed change gives precedence to the "Hardware" setting, if found.
In the 3 phones tested, the CPU output name will change (from → to):
ARMv7 Processor rev 3 → Hisilicon Kirin 920
ARMv7 Processor rev 3 → Qualcomm MSM8926
AArch64 Processor rev 12 → Qualcomm SDM845
Which in fact was just the previous output (I find it more adequated) to report these devices's CPU.
=> give precedence to "Hardware" entry in /proc/cpuinfo

neofetch
a patch for supporting i3buntu, an ubuntu-based distro that doesnt have an own logo
displays the ubuntu logo for i3buntu
=> Added a case for displaying the Ubuntu logo for i3buntu.

neofetch
Apple added `BuildID` to `/System/Library/CoreServices/SystemVersion.plist` as the first key with iOS 11.3, thus the array indices of `sw_vers` are off by 1 in iOS 11.3 and later.
This PR changes the way neofetch reads information from `SystemVersion.plist` by searching for the keys `ProductName`, `ProductVersion` and `ProductBuildVersion` instead of assigning data from hard coded array indices, thus making it more robust to future changes to this file.
This PR fixes #1061. The issue was closed, but should've been reopened by the author.
=> cache_uname: fix darwin_name and osx_version for iOS 11.3 and later + add model,cpu,gpu for some idevices

neofetch
Closes #1243 
At least on Nix, it's not clear what is a "package" is. Is `/nix/store/5f19dgkp4ly35a1f7mmzlli7x356hlm2-user-environment` a package? It's listed, at least.
Also, for Nix there's `nix-env -qa` as an alternative, but it's *very* slow.
N/A
=> Packages [Guix/Nix]: Switch to commands instead of using directories

neofetch
Since Android 9 the uptime is returned as empty string.
This is due to new permissions restrictions (see https://www.cl.cam.ac.uk/~rja14/Papers/interrupts_pets16-1.pdf)
The proposed change fails back in these cases to the uptime command and has been tested with `/system/bin/uptime` (which supports the -s option in Android 9), the uptime busybox applet (Termux) as well as the uptime command from procps-ng.
=> support uptime from Android 9+

neofetch
https://github.com/dylanaraps/neofetch/pull/185 just use `[ -f "${GTK2_RC_FILES:-$HOME/.gtkrc-2.0}" ]` as the condition which will fail when `${GTK2_RC_FILES}` have multiple values.
For me, it is `/etc/gtk-2.0/gtkrc:/home/edward/.gtkrc-2.0:/home/edward/.config/gtkrc-2.0`, which causes wrong GTK2 theme detected.
Fixed GTK2 theme ditection when ${GTK2_RC_FILES} contains multiple values.
=> Handle GTK2_RC_FILES with multiple values

neofetch
Red Hat recently (May 2019) updated its official logo and brand standards, and the new logo is now a slightly different shaped fedora _without_ the shadowman figure beneath it. 
You can see the new logo here: https://www.redhat.com/en/about/brand/standards
This PR just swaps the old logo with a representation of the new logo. I used an online image-to-ASCII generator with Red Hat's new logo and then cleaned up some bits by hand.
=>  update Red Hat with new 2019 logo

neofetch
This adds an option for public IP retrieval via lightweight `drill(1)` from the [ldns](https://nlnetlabs.nl/projects/ldns/about/) package.
`drill` is a minimalistic, still feature-rich alternative to `dig` from developers of [NSD](https://nlnetlabs.nl/projects/nsd/about/).
- public_ip via `drill(1)`
- it doesn't have any "short" option, hence an `awk` hack
=> Retrieve public IP info via drill

neofetch
Work for multiple GPUs now
1. Replace `\\"` with `\"`, otherwise awk warns `\"' is not a
known regexp operator
2. Use the slot number of `lspci -mm` return value to
determine whether two video cards are in different PCI slots,
and therefore are two different GPUS.
=> Works for multiple GPUs now

neofetch
As mentioned in #1193, the current implementation doesn't work for me. In my settings, the font is Iosevka Term SS08. And if I won't get the full font name.
=> Fix kitty font parsing when font name has whitespaces

neofetch
This prevents package managers showing up as having installed 1 package,
while it's actually 0.
=> Set nullglob for package counting

neofetch
Only fill in the fields below if relevant. Basically [this PR](https://github.com/dylanaraps/neofetch/pull/1265) which fixes this [issue](https://github.com/dylanaraps/neofetch/issues/1267) done right. It could still have issues thinking a distro is guixsd if the guix package manager is installed and it is still a unknown distro
=> Moved guix check below /etc/os-release check

neofetch
Recently Ataraxia Linux moved to kagami package manager. And I've added support for it!
=> add support for kagami package manager

neofetch
Fixed wrong offset and missing colour for SailfishOS which also closes and finishes #1270
=> Linux: Fix ASCII for Sailfish OS

neofetch
Changed the blue used in the Feren OS logo as most colour schemes made the logo appear to be teal instead of blue.
Following on from the change that added the Feren OS Logo, I installed Neofetch from Git Master to check what the logo looked like, and the only issue I can see with it is its colour choice before applying this Pull Request's changes. On most colour schemes in Feren OS Next, for instance, the current colour choices led to the logo being displayed in a teal colour, which looks odd for a blue logo. Having then checked the Fedora ASCII Logo (which is above this logo in the code), I realised that that blue fits better for the Feren OS Logo than the teal does.
On all the colour schemes I've tried thus far with this change the blue used perfectly fits with the Feren OS logo after …
=> Small tweak to the colours used for the Feren OS Logo

neofetch
`ksh` and `mksh` are not the only versions of ksh. 
there are also `pdksh`, `oksh`, `loksh`, `ksh{95,98,?}`, etc... While their bin *may* be named `ksh`, its not guaranteed.
This glob allows for detection of any `*ksh` shell, whatever its bin name is.
before: http://ix.io/1Px8.png
after:   http://ix.io/1Px9.png
=> support other versions of ksh

neofetch
=> display_image: Allow Chafa backend to stretch image to desired size

neofetch
Homebrew officially supports Linux since 2.0.0 release.
I used `brew --cellar` instead of a fixed directory, because one can install Homebrew on Linux in whatever directory one desires, though `/home/linuxbrew/.linuxbrew` is the blessed one.
Show brew packages count on Linux.
=> packages: Check brew on Linux

neofetch
GuixSD is known as Guix System these days¹, so I updated the script accordingly.
1. https://guix.gnu.org/download/
=> Rename GuixSD to Guix System

neofetch
As of v2.8.0 cmus supports mpris2, so `get_song_dbus` could be used to query song info.
Until v2.8.0 has made it's way into the (major) distros add a comment as reminder. Perhaps debain stable is a good indicator for the switch?  :see_no_evil:
=> song: add comment about cmus mpris support

neofetch
According to #1342 Guix was renamed from GuixSD to Guix System and the ascii logo is not shown.
Reduced the matching to "Guix"* instead of "GuixSD"* to fix this. For consistency also renamed the small logo.
=> Fix Guix ascii not shown

neofetch
Fix Plasma themes detection. Not working since the rename `KDE -> Plasma` in #1289.
=> style: fix Plasma themes

neofetch
This adds a command-line and/or configuration file flag to specify an arbitrary position for the color columns. It defaults to auto, which reproduces the default behavior of neofetch. It can also be set to an integer, N, which will print the columns starting at N spaces from the left side of the terminal. This is useful for users whose information is larger than their distro ascii or associated photo, and gives them a way to increase the symmetry of the output if they choose.
=> Add option to arbitrarily position color columns

neofetch
i got annoyed how bad --help was for --ascii_distro so 
i got all names in there for old varients, ubuntu flavors, and small varients 
i got a error when doing neofetch --ascii_distro "POP!_OS" so i made another one saying pop_os without exclamation mark cuz thats what made the error
no rhel_old annoyed me
fixed dragonfly_old cuz it had a weird line which i disliked
=> updated --help

neofetch
Unity is still the default Desktop in Ubuntu 16.04 LTS which has support until April 2021.
=> de_version: Add Unity

neofetch
* Added WM detection (Mutter) on GNOME Wayland
* Added Openbox theme detection on LXQt
Also:
* Removed `GNOME Shell` from a WM case as it's renamed to `Mutter` anyway.
* Changed the `awk` command in Openbox theme detection to be more robust.
It failed when there were other lines (e.g. comments) between the `<theme>` and `<name>` lines in the config file. That was the case in Lubuntu default config for example.
* And finally refactored the Openbox theme detection to look nicer with the LXQt addition.
=> Detect Mutter on GNOME Wayland and Openbox theme on LXQt

neofetch
In Konsole 19.12.0 `KONSOLE_PROFILE_NAME` was removed from `environment` and replaced with dbus method `profile()`.
* Added a line to use the new `profile()` method if `$profile` is empty after grepping for `KONSOLE_PROFILE_NAME`.
* To avoid printing wrong font info  return early if getting the profile name fails. 
* Removed some quotes for consistency.
=> Fixes and updates for Konsole font detection

neofetch
Get wallpaper for Plasma desktop from ~~`${XDG_CONFIG_HOME}/plasma-org.kde.plasma.desktop-appletsrc`~~ `${XDG_CONFIG_HOME}/plasmarc`.
Tested with KDE Plasma 5.17.4 on Arch Linux.
=> Get wallpaper for Plasma desktop

neofetch
* Fixed a bug with Exaile song query when artist, album or title contains a `,`. 
broken
fixed
* Also removed stripping of `file://` from Plasma wallpaper path. It's done at the end of the function anyway.
=> Fix Exaile song query and remove redundant trim

neofetch
Song info was incorrect whith empty tags.
For example empty 'album' tag.
`some artist - some title - Unknown Song`
But it should be
`some artist - Unkown Album - some title`
Tested with all `non get_song_dbus players` except `muine`. Perhaps we should remove `muine`
entirely, it is a dead project and I was not able to install it for testing.
Tested with some `get_song_dbus players`, but should work with all.
I did not change the Apple players (spotify on MacOS and itues) because I cannot test.
Simplified the `cmus` query.
=> song: print empty tags correctly

neofetch
This PR enhances `get_term_font()` by checking if `$term` matches with `conemu-*` and sets `$term_font` accordingly. Settings scanning is done according to [ConEmu's settings search sequence](https://conemu.github.io/en/ConEmuXml.html#search-sequence)
* `$APPDATA/ConEmu.xml` file :
* ConEmu's `-LoadCfgFile` argument :
* `HKEY_CURRENT_USER\Software\ConEmu\.Vanilla\FontName` value :
* This enhancement relies on `get_term()` which can't detect ConEmu if its [Cygwin/MSYS connector](https://conemu.github.io/en/CygwinMsysConnector.html) is not used.
* Very basic XML parsing is done on `ConEmu.xml` settings file. Font detection might silently fail if the `<value/>` node is `\n`-splitted. However, the default file structure is ok.
=> Added font detection for ConEmu

neofetch
Previously, AMD CPUs with numeric core values (for example 3rd-gen Ryzen CPUs) had their CPU name cut off incorrectly:
This patch fixes the problem:
=> Add patterns for AMD CPUs with numeric core counts

neofetch
I noticed our #t2sde, formerly knows as ROCK Linux was missing, so I added it ;-)
=> Added initial t2 Linux support

neofetch
This pair of commits fixes some FreeMiNT-specific issues:
1. Removes a number of FreeMiNT-specific color fixes that aren't strictly necessary
2. Checks for the presence of _xaloader_ in processes to detect XaAES when loaded via kernel module (as it is in current versions)
3. Blocks using X11 resolution checks since these checks will lock up with the default X11 tools on FreeMiNT if the X server isn't running and will be incorrect if X/GEM is running
4. Fixes the memory info on current kernels and Bash versions
5. Strips machine cookiejar identifier from the model info
=> FreeMiNT-specific fixes and updates

neofetch
Previous output: `OS: OpenBSD 6.6 amd64`  
Changed output: `OS: OpenBSD 6.6-current amd64`
If not running current, simply `OpenBSD 6.6` is printed.
full text output of the command used:
```sh
% sysctl -n kern.version
OpenBSD 6.6-current (GENERIC.MP) #40: Sun Mar  8 20:17:34 MDT 2020
deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
%
```
=> detect whether using -current on OpenBSD

neofetch
Add ascii logo for OpenStage Linux.
https://www.openstagelinux.org/
https://gitlab.com/openstage-packages/community/screenfetch-os/-/blob/master/ascii2
=> os: Add OpenStage Linux

neofetch
Prefer `/etc/gtk-3.0/settings.ini` to `/usr/share/gtk-3.0/settings.ini`.
Currently, it checks `/usr/share/gtk-3.0/settings.ini` first; this causes it to misreport my GTK 3 theme, which I customized in `/etc/gtk-3.0/settings.ini`.
Curiously enough, for GTK 2, it already checks `/etc/gtk-2.0/gtkrc` first, so it already gets my GTK 2 theme right.
=> Change order GTK3 settings.ini files are read

neofetch
Not sure if it should use the current `$OIL_VERSION` if it exists and if `$BASH_VERSION` should only be set if the `$SHELL` is `bash`.
=> neofetch: add support for OSH

neofetch, neofetch.1
Added the [Alter Linux](https://fascode.net/en/projects/linux/alter/) and [Serene Linux](https://fascode.net/en/projects/linux/serene/) logos.
I didn't quite understand the format of the commit message.I apologize.
I am Japanese and I am not very good at English. I am using Google Translate for this sentence.
=> Added support for Alter Linux and Serene Linux

neofetch
es shell doesn't have any way to check the version, so I added it to the shells that ignore `--shell_version on` in this simple commit.
=> Add es shell support

neofetch
Adds support for the [playerctl](https://github.com/altdesktop/playerctl) music player controller.
Adds support for [playerctl](https://github.com/altdesktop/playerctl).
Doesn't get precedence over other music players when using `music_player="auto"`.
=> Add playerctl support

neofetch
Support for both "Mac OS X" and "macOS"
Support for macOS 10.16(11.0), Big Sur
Resolve issue #1486 
The new macOS version, Big Sur, officially announced as 11.0, but according to `/System/Library/CoreServices/SystemVersion.plist`, its version is 10.16. So I made both works well.
=> Add latest macOS support and fix issue

neofetch
Didn't know that it's a requirement that we use only colors 0-16.
This reverts the colors for Xubuntu and Lubuntu back to 4.
=> ascii: revert colors

neofetch
Exaile 4.0.0 was released more than a year ago (06 Jun 2019). Since it is not packaged in debian stable/testing/sid at all, I think switching to MPRIS should be ok now.
=> song: Switch Exaile to get_song_dbus

neofetch
Added another possible name to the regex for finding cpu temperature.
This was tested on a Raspberry Pi 4 running Arch Linux ARM.
Should fix #1463
=> Fix CPU Temp. not showing up on Raspberry Pi

neofetch
See: #1569 
This is a PR to re-implement `catimg` support. It also fixes a bug with the previous implementation where one of the optional size parameters could make the image overflow into the text.
`shellcheck` passes and all (modified) lines are below 100 characters.
=> catimg support

neofetch
Better handling of Wayland desktops
Corrects detection of Wayland compositors when `WAYLAND_DISPLAY` is unset
Doesn't identify window managers belonging to other user session
The logic for BSD is unchanged (I'm too lazy to set up a test system)
Fixes: #1500
=> Better handling of Wayland compositors

neofetch
Fix as per #1448.
Blank lines after invocation are now consistent across distro ASCIIs and through either `--color_blocks` setting.
=> Remove extra newlines from get_cols

neofetch
Fixed bug of wrong count of packages installed by some package managers (tested on scoop and snap). The fix is in branch _packagenum_
Fixes: #1274
=> Wrong number of packages reported for some package managers

neofetch, neofetch.1
This PR adds Überzug image support. [Überzug can be found here.](https://github.com/seebye/ueberzug)
Überzug support added. Tested and working under st. Relevant comments and man page documentation included.
Related issues that requested and discussed this.
#1172 #1392
=> Überzug image support

neofetch
Hi,
Here are small fixes: 
`glxinfo` is taking a major part of the global neofetch' run time here, using the `-B` flag is enough to get the GPU. On 100 iterations, it's 2 times faster!
Looks like other OSes use "%2.1f",  but OpenBSD uses "%2.2f". I had the cpu at 3725°C instead of 37.25°C.
While here, i've added [adt(4)](https://man.openbsd.org/amd64/adt.4) and the more recent [ksmn(4)](https://man.openbsd.org/amd64/ksmn.4).
=> Improve glxinfo call, OpenBSD sensors fix

neofetch
This add [viu](https://github.com/atanunq/viu) image backend. 
I added this because Überzug was not working for me (alacritty + sway/wayland). 
Image can now be rendered under wayland (low definition but still). 
Still need to document this in the wiki (how to I do it ?)
=> feat(backend): add viu image backend

neofetch
Instead of breaking after the first-found non-empty `/sys/class/drm/*/modes` file, process all of them by pre-pending values to the `resolution` string. This is able to correctly show the four attached displays on my workstation running Sway, rather than only the display on the first DisplayPort output. I've also tested this on a laptop with only the built-in display, running Sway.
=> Support multiple displays under wayland

neofetch
`swupd` is the default package manager of Clear Linux OS (they actually call their packages bundles). This patch adds support for swupd.
=> Add support for `swupd` package manager

neofetch
Originally added in #1063, but did not actually work because it only
looked for konsole processes (rather than yakuake's) when querying its
session profile.
=> Fix font support for yakuake

neofetch
Take pagesize into account when calculating free memory on macOS, since Apple Silicon machines have a pagesize of 16384, in contrast to all (Intel) Macs before, which had 4096.
This also changes how [the calculation itself](https://apple.stackexchange.com/questions/258166/what-is-app-memory-calculated-from) works, to more accurately report what is being shown in the Activity Manager.
Fixes #1663,  #1674
=> Rework macOS memory calculation to work on Apple Silicon

neofetch
changes /usr/local/Cellar to "$(brew --cellar)" as used on line 1550
#1746 
~~Someone with a non-M1 mac should verify this has no issues for them~~ (done)
=> fix neofetch not recognizing brew package count on M1 macs

neofetch
It seems like there is no option to use a custom address for getting the public IP address if _dig_ or _drill_ is installed.
This request changes this to always use the public_ip_host variable if it's set, and if it's empty then DNS will be used.
public_ip_host="" -> uses DNS for getting public IP
public_ip_host="http://example.com/ip" -> uses wget/curl for getting public IP
=> Only use DNS if public_ip_host option is empty

neofetch
This adds support for APT/dpkg package manager for macOS when being used.
Added support by providing information for new iOS and iPadOS devices. [This was initially apart of PR# 1702](https://github.com/dylanaraps/neofetch/pull/1702)
This add the number of APT/dpkg packages installed on macOS.
This will allow for Host, CPU, and GPU tags to display correct and accurate information for newer iOS and iPadOS devices. Huge thanks to @NotZoeyDev for providing this information about the new devices.
=> Added APT/Debian Packager to package managers for MacOS and combined PR #1702

neofetch
Neofetch is Bedrock-aware by default, but ignores Bedrock and restricts itself to the local layer of the Bedrock system when run in Bedrock's "restricted" mode.  Previously, neofetch checked for restricted mode by looking at the $PATH, which can fail in some workflows.  Instead, check for $BEDROCK_RESTRICT, which is more robust.
Neofetch previously counted Bedrock stratum aliases when counting packages for some package managers.  This resulted in over-counting packages.  This commit restricts neofetch to only counting actual strata, not aliases.
=> Bedrock Linux fixes

neofetch
This commit provides PuffOS distro into neofetch. Instead of #1659 it is well generated little patch. This patch provided from developers of PuffOS and adds PuffOS logo
https://puffos.github.io
https://puffos.github.io/puffmixsized.png
Added PuffOS into table
No issue seen
Not any actual TODO
=> Added PuffOS successfuly instead of #1659

neofetch
The main version file of GNU/Deepin Linux has been moved from /etc/deepin-version to /etc/os-version.
n/a
n/a
n/a
=> fix: GNU/Deepin Linux Version file

neofetch
My ~/.minttyrc has:
```
BoldAsFont=-1
Font=Lucida Console
FontHeight=10
```
so neofetch reported:
```
Terminal Font: -1
```
This patch fixes it:
```
Terminal Font: Lucida Console
```
This patch does not address that ~/.minttyrc can be moved to ~/.config/mintty/config per https://mintty.github.io/mintty.1.html#CONFIGURATION, or default to the Font specified in /etc/minttyrc, if it exists.
=> neofetch: Fix Terminal Font for mintty

neofetch
Fix PCLinuxOS logo alignment
PCLinuxOS logo was misaligned. (this is on my openSUSE laptop with `--ascii_distro pclinuxos` passed as argument)
So I fixed it
=> Edit PCLinuxOS logo for proper alignment.

neofetch
Since [Homebrew 2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/), Homebrew supports Apple Silicon. Now Homebrew installs on different locations depending on CPU architecture.
From brew man page [--cellar](https://github.com/Homebrew/brew/blob/master/docs/Manpage.md#--cellar-formula) and [--prefix](https://github.com/Homebrew/brew/blob/master/docs/Manpage.md#--prefix-formula):
> ### `--cellar` [*`formula`*]
> 
> Display Homebrew's Cellar path. *Default:* `$(brew --prefix)/Cellar`, or if that directory doesn't exist, `$(brew --repository)/Cellar`.
> ### `--prefix` [*`formula`*]
> 
> Display Homebrew's install path. *Default:*
>
>  - macOS Intel: `/usr/local`
>  - macOS ARM: `/opt/homebrew`
>  - Linux: `/home/linuxbrew/.linuxbrew`
The current code doesn't count brew packages on ARM Mac, …
=> Fix Homebrew's Cellar path for brew package counts

neofetch
This change is limited to OpenBSD only, and related to cpu reporting improvements as seen in https://github.com/dylanaraps/neofetch/issues/1574
Instead of using [hw.ncpu](https://man.openbsd.org/sysctl.2#HW_NCPU~2), use [hw.ncpuonline](https://man.openbsd.org/sysctl.2#HW_NCPUONLINE~2) and [hw.ncpufound](https://man.openbsd.org/sysctl.2#HW_NCPUFOUND~2), and check [SMT](https://man.openbsd.org/sysctl.2#HW_SMT~2) status.
I confirm that "physical" is not available on OpenBSD.
```bash
$ sysctl hw.smt
1
$ neofetch
[...]
CPU: AMD Ryzen 5 2600 (12/12, SMT on) @ 3.400GHz
[...]
$ doas sysctl hw.smt=0
$ neofetch
[...]
CPU: AMD Ryzen 5 2600 (6/12, SMT off) @ 3.400GHz
[...]
```
There is not enough context ootb in the GH diff view, i had to inject non breaking spaces because regular spaces are filtered …
=> OpenBSD: change cpu count (#1574)

neofetch
After this change, if a subsystem name exists for a GPU, display that name instead of the device name. This should fix the issue mentioned in #1490. For example, a card that would be shown as `GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590` before will now be shown as `GPU: AMD ATI Radeon RX 480 4GB`. This fallback logic is implemented in the `awk` command.
Additionally, the PCI address is now stripped from the awk output because it never is desirable to print it. It is, however, still kept internally in `awk` to distinguish multiple cards of the same model.
Implements #1490.
=> Show GPU subsystem name if possible

neofetch
Linux on SPARC expose CPU core and frequency information on different places.
This makes neofetch read from the correct places on SPARC.
=> Fix CPU core/frequency reading on Linux/SPARC systems

neofetch
Hi!
This bug has been introduced by 370a50c3e36b091dc2dc2f6cd9161477f3638b31
When running neofetch HEAD, i meet this:
```
./neofetch: line 3310: syntax error near unexpected token `newline'
./neofetch: line 3310: `"ruby"|"1"|"tmux"*|"systemd"|"sshd"*|"python"*|'
```
The spanning seems to miss a '\\'
=> Unbreak the runtime, fix a wrong multiple line spanning

neofetch
Fixes neofetch only counting homebrew formulae for the package count
#1776
=> fix package count not including brew casks

neofetch
The current way of getting kitty's terminal font won't work on v0.21.0 and later due to the removal of `--debug-config`. However, the author provided a more precise way to query the current config. More info can be read at kovidgoyal/kitty#3756.
This change is backwards compatible (and tested) with older versions of kitty.
=> Better kitty terminal font detection

neofetch
=> fix macos big sur and monterey not showing codenames

neofetch
LangitKetujuh GNU/Linux based on voidlinux.
homepage: https://langitketujuh.id
Terminal:
Splash screen logo:
=> Add LangitKetujuh OS

neofetch
debian 11 has been released, so I think we can switch song info for cmus to get_song_dbus now.
=> song: Switch cmus to get_song_dbus

neofetch
Fixes #1835
`pac` does not increment `$packages`, so the current command is broken.
This `dpkg-query` command is actually already in-use for macOS, and pfetch also uses it for both Linux and macOS.
https://github.com/dylanaraps/neofetch/blob/5dc9a2fa61719efc3e9614e44d9d8df5d9043c8d/neofetch#L1643
=> packages: fix dpkg

neofetch
Make small changes to make them more consistent with the actual Apple logo, fixing issue #1865
Current:
New:
From #1865:
Line | error | Replace with
--|--|--
line 1 | `'c.` | `.c'`
line 5 |  `'` | `.` or `,`
line 5 | `looll` | `<space>.oll`
line 13, 14 | `.XMM` | `'XMM`
line 4 | `OMMMO,`| `lMM"`
last line | `.cooc,.`| `"cooc*"`
last line | `.,coo:.`| `"*coo'"`
=> Update Apple logos - Issue #1865

neofetch
GPUs that have subsystem name but no revision number can be processed
correctly by using $(NF-1) instead of $7 in the awk
Since these don't have a revision number, their $(NF-1) becomes $6
=> Improve GPU Reading on Linux

neofetch
Use /sys/devices/virtual/dmi/id/board_vendor / board_name for motherboard identification if available. Fixes issues when product_name/product_version are not available.
=> Use /sys/devices/virtual/dmi/id/board_*  for motherboard identification

neofetch
Currently, neofetch looks like this for nushell users
This fixes the issue so that it now looks like this
=> Add support for nushell
