dylanaraps/neofetch

- config/config
- fetch
> Changed image cache location

- 1.2.md
BTW Dylan I have just reset my fork repo and I saw that you were watching so you need to click "watch" again.
> Fixed typo

- README.md
- fetch
See issue number **#75** for the reasoning behind this.
> Make 'wmctrl' a required dependency.

- README.md
> Changed my screenshot

- fetch
> Add Battery Support for FreeBSD

- fetch
This PR disables the creation of the config file in stdout mode.
Please test this @tudurom.
> Don't create a config file in stdout mode.

- 1.4.md
- Makefile
- README.md
- neofetch
This PR renames `fetch` to `neofetch`. 
TODO:
> Rename fetch to neofetch

- 1.4.md
- README.md
obviously they aren't applicable just yet :P
> Added OS X install instructions

- 1.5.md
- README.md
- config/config
- neofetch
- neofetch.1
usage: --cpu_shorthand (name, model, name_model, speed)
also edited config file to suit
addresses #130
documentation updates to come
> added ability to shorten cpu output

- neofetch
bash dependency is fixed in preamble too lol
> added working birthday function for OS X

- neofetch
I'll fix the documentation in the morning
Also brings a portion of `cpu_shorthand` into this branch, shouldn't cause issues? Need to set defaults too
> Progress bars fixes

- neofetch
> Iterm2 image rendering fixes

- README.md
- config/config
- neofetch
- neofetch.1
I seem to have accidentally pulled in the iterm2 fixes. Oops.
> OSX Codename support

- README.md
- config/config
- neofetch
- neofetch.1
I guess adding the CPU cores to the CPU output would be possible now too.
Still need to add NetBSD and Windows support though.
> added cpu cores so the usage bar doesn't go crazy above 100%

- neofetch
> added /usr/share as a gtk theme directory

- 1.5.md
> Changelog typo fix

- README.md
ZSH interprets `?` as wildcard, so i've added quotes in curl instruction. Additionally i've made some cosmetical changes
> added quotes in curl + small cosmetical changes

- neofetch
adds an extra option before the `curl` and `wget` commands that uses `dig`
> Made publicip function faster by using dig

- README.md
- neofetch
Adds optional dependency `gpmdp`
> Added Google Play Music Desktop Player as a song output source

- neofetch
This PR aims to fix issues with neofetch on OpenBSD.
Issues:
> OpenBSD fixes

- README.md
> added License badge to README

- .travis.yml
- README.md
- neofetch
the resolution block for if not using `screenresolution` could probably be made a lot smaller too.
also fixed a few of the dependency lines.
> made resolution way faster on OS X

- config/config
- neofetch
> Color progress bars based on distro logo colors

- neofetch
This speeds up the scipt a little when using ascii mode.
TODO
- Test on OS X.
> Use awk to get ascii size.

- neofetch
could probably be made faster still, but the main culprit for speed reduction is gone
> made OS X packages SUPER fast

- 1.6.md
- neofetch
Yo
- Each ip source now has a timeout
- If one ip method fails we fallback to another
> Changes to the public ip function

- README.md
A nice indicator for latest release :smile:
> added Release badge to README

- 1.7.md
- neofetch
> Better DE detection.

- neofetch
- Move distro detection to a seperate function
> Moved getdistro to a seperate function take 2

- 1.7.md
- config/config
- neofetch
Made progress bars more customizable.
- Set the elapsed and total char.
- Add a border option.
- Also changes default progress bar look as the old default didn't work in older systems.
> Made progress bars more customizable

- README.md
> updated ubuntu installation instructions

- README.md
- neofetch
This PR aims to add support for iOS. (iPhone, iPod, iPad)
TODO:
- ~~iOS is detected as Mac OS X right now.~~
- ~~I need help with this one as I don't have an iPod or iPad to test on.~~
- ~~Low priority, will be fixed after PR is merged.~~
Other:
Dependencies:
- `Core Utilities`
- `Core Utilities (/bin)`
- `Darwin Tools`
- `system-cmds`
- `bc`
- `Gawk`
- `grep`
Current neofetch master:
> Add iOS Support

- neofetch
Edited the WMIC command used so that the screen resolution can be obtained on Windows 10.
> Support screen resolution on Windows 10

- neofetch
Still waiting on iTerm2 support for using AppleScript.
> added apple terminal font support

- neofetch
This PR quotes all variable and command substitutions.
> Quote all the things

- README.md
Untested in Funtoo, but I think it should work.
> New installation instruction for Gentoo/Funtoo

- neofetch
This fixes issues with how we place the prompt during image mode.
> Fix prompt location issues in image mode

- ascii/distro/openindiana
- ascii/distro/oracle
- neofetch
Included:
* Added Oracle logo (and color)
* Small color tweak on OpenIndiana's logo (and colors)
> Updates on ASCII logos and colors

- neofetch
This simplifies the speed and cores commands for Solaris.
@konimex, can you confirm that these work on your Solaris system?
> Solaris: Simplify CPU commands

- neofetch
Fixes various issues with the new config file handling and also moves everything to a function that gets called from `main()`.
> Config fixes

- neofetch
This PR adds support for macOS in the new model function
> added macOS support for model name

- neofetch
This PR adds Solaris support for model function.
> Added Solaris support for model

- neofetch
> Some OpenWRT fixes

- neofetch
Reverts dylanaraps/neofetch#318
> Revert "Some OpenWRT fixes"

- neofetch
Included:
- Added model support for Android
- Changed CPU command to use native Android ones
> Added and changed some Android commands

- README.md
> Updated README with Solaris dependencies

- neofetch
Latest output after this commit:
> Fixed Android uptime

- ascii/distro/solus
This is a fairly little change. Sorry for bothering again :/
> Make the Solus logo a bit smaller

- neofetch
A pretty trivial one. Just fixed some indentations (3 spaces instead of 4, something like that).
> Fixed various indentation

- neofetch
> fix macOS to show physical cores

- neofetch
- Show `WM: $wm, Explorer`
- Blackbox: Specify bbLean `WM: bbLean (Blackbox), Explorer`
> wm: Windows tweaks

- neofetch
This reduces the size of the case statement.
> Condense osx_version

- ascii/distro/void
fixes to make more like original screenfetch ascii
> update void ascii

- neofetch
Fixes
- Packages: Fix `if` syntax.
- WM: [Windows] Condense test.
- CPU: [iOS] Rewrite CPU function.
- GPU: [iOS] Rewrite GPU function.
> Misc fixes/changes

- config/config
- neofetch
Rewrote and simplified the battery function on Linux systems. 
Removed two Linux only options as they aren't needed anymore.
> Battery: [Linux] Rewrite battery

- neofetch
Rewrite song function to check process list once instead of multiple times. This speeds up the entire function.
Testing:
> Song: Rewrite song function

- README.md
- config/config
- neofetch
- neofetch.1
Features:
- Simpler
- Faster(?)
- The output is cached until next boot.
TODO:
> GPU: [Linux] Rewrite GPU

- ascii/distro/rstar
- neofetch
친애하는 지도자 김정일의 위대한 후계자가 김정은이 프로그램 neofetch에
영광스러운 붉은 별의 검출을 추가 요구했다, 당신은 더 나은 자신의
명령을주의 나 기회가 될!
Signed-off-by: Korea Computer Center (조선콤퓨터쎈터) <admin@kcc.net.kp>
> 레드 스타 OS에 대한 도움 탐지

- README.md
- neofetch
For the README I forgot to include Android in the Installation ToC, so my apologies beforehand. I had to do this from mobile using GitHub web interface and it was absolutely painful.
> Various updates for Android/Termux

- neofetch
I'm having another crack at sourcing the *ease files instead of the various awk commands. I'm including a fallback for distros that go against the os-release standard.
> Distro: [Linux] Source *ease files

- neofetch
Cleanup/Rewrite of some functions.
> General: Function cleanup

- neofetch
> Misc: Fix lint errors

- config/config
- config/travis
- neofetch
Changes all vars/functions to this format: `var_name`
- ~~This will break user configs~~
> General: Change all vars/functions to use underlines

- neofetch
I don't know how much of a difference this makes but from what I've read online it's the correct way of comparing numbers in bash.
> General: Convert math tests to correct syntax

- neofetch
This adds package detection for both Lunar Linux and Tiny Core Linux.
> Packages: Added package detection for Lunar Linux and TinyCore

- neofetch
Possibly fixes memory bug in #453
> Memory: Change math to fix possible bug

- neofetch
> Packages: Remove /usr/games from PATH to fix issues with pacman game

- config/config
This PR will rewrite all of the config file docs, hopefully making them easier to understand/configure for new and existing users.
Changes:
- Created a format for each option to use.
- Added default value to every option.
- Separated Flags/Args.
- Added examples of what each option does.
> Config: Rewrite docs

- config/config
Added some clarifications since more OSes are supported with those two flags.
> Config: Updated description

- neofetch
> GPU: Fix wrong AMD GPU detected

- neofetch
> GNU Hurd: Added uptime

- neofetch
> GPU: [Linux] Prefer dedicated card over integrated card.

- neofetch
Self explanatory. This should make the script faster when a second iteration of neofetch is being run.
> Public IP: Add caching

- ascii/distro/ubuntu
This updates the Ubuntu ascii art to the latest logo.
> Ascii: Update Ubuntu logo

- neofetch
This PR rewrites the BSD memory function to fix an issue with FreeBSD.
> Memory: [BSD] Rewrite BSD memory function. 

- neofetch
- Rewrite wallpaper function
- Prioritize DE wallpaper setters before falling back to feh/nitrogen.
- Added support for XFCE's wallpaper setter.
> Wallpaper: Rewrite wallpaper functon.

- neofetch
> Wallpaper: Expanded support to Solaris and GNU Hurd

- .travis.yml
- neofetch
The goal of this PR is to integrate `shellcheck` into our travis builds.
- Adds `shellcheck` to the linux tests.
- Fixes `SC2068`
- Fixes `SC2086`
- Fixes `SC2076`
> Travis: Add shellcheck

- neofetch
Code is self-explanatory. Just a small detail.
> Colors: use start++ instead of adding it manually after case

- neofetch
Add support for xmms2 in `get_song()`.
> Song: Add support for xmms2

- neofetch
> DE: Fix cases where WM == DE

- neofetch
> Kernel: Simplify check

- neofetch
Added support for JuK and Bluemindo players.
> Song: Add support for JuK and Bluemindo

- neofetch
Adds support for sakura terminal font.
> Term: Add support for sakura font

- neofetch
Adds support for Guayadeque player.
> Song: Add support for Guayadeque

- neofetch
Adds support for konsele font detection. Needs get_ppid() from #562
> Font: Add support for Konsole

- neofetch
This PR adds decoding to the `gsettings` wallpaper commands that include `picture-uri`.
Closes #573.
> Wallpaper: Decode gsettings file paths, closes #573

- neofetch
> General: Fix arithmetic expression

- neofetch
Fixes KWin Theme detection and config directory for KDE/Plasma 5
>  Fix WM Theme detection for KDE5, closes #586

- neofetch
> ASCII: Fix SUSE logo not displayed

- neofetch
- Fixes hang caused by missing OS ascii art.
- Fixes wrong text padding in no ascii/image mode.
> Ascii: Fix hang caused by missing OS ascii art.

- neofetch
> General: Swap some math to simpler syntax

- neofetch
This PR adds song retrieval capabilities for the semi-popular music Server "mopidy"
- Outputs songinfo just as mpd would
> Song: added mopidy compatibility for the Song info

- neofetch
Title.
This PR also alphabetizes the terminals in `term_font()`.
> Term Font: Added support for Alacritty.

- neofetch
Adds support for QuodLibet ...
> Song: Add support for QuodLibet

- CHANGELOG.md
- ascii/distro/aix
- neofetch
This adds support for AIX systems, most of the functions have worked as intended.
We'll have to rely on external source (our current primary source is #591) since we don't have access to any AIX systems, be it from a VM, or a physical one.
> OS: Added initial support for AIX

- Makefile
- neofetch
Self-titled.
If this looks good enough, please merge it (and update the changelogs accordingly) as I won't be able to open my desktop for the next 6-8 hours.
> Config: Move default config to /etc (#620)

- neofetch
Adds font detection for deepin-terminal.
Tested on Arch and Deepin.
> Term Font: Add support for deepin-terminal

- movies.txt
- neofetch
This PR makes functions using `prin` only append to the subtitle if it exists.
Fixes #636
> Output: Fix output when user disables subtitles.

- ascii/distro/parabola
I think the new logo is closer to the original.
old
new
> Ascii: Parabola logo

- neofetch
This PR adds support for [Kwm](https://github.com/koekeishiya/kwm).
> WM: Add support for Kwm on macOS

- neofetch
Reverts dylanaraps/neofetch#658
> Revert "WM: Add support for Kwm on macOS"

- CHANGELOG.md
- neofetch
> OS: Added support for MinGW

- neofetch
> W3m: Fix zero width space outputting garbage.

- ascii/distro/arch_xferience
- neofetch
https://sourceforge.net/projects/arch-xferience/
> OS: Add support for Arch XFerience

- ascii/distro/maui
- neofetch
> OS: Add support for Maui

- neofetch
Reverts dylanaraps/neofetch#732
This PR broke Travis.
Please make sure the build passes before merging PRs.
> Revert "Model: Add support for Hackintosh"

- neofetch
Further testing recommended as I've only tested it in my Termux device.
> Term: Break from loop if PPID can't be accessed/not found

- neofetch
> scrot: Skip "import" on MacOS

- neofetch
Fixes the issues with KDE themes in #766
> Fix KDE themes

- CHANGELOG.md
- config/config.conf
- neofetch
- neofetch.1
The first commit is under the hood changes, so no changelog is needed.
> CPU: Various CPU changes

- neofetch
> General: Get rid of a call to awk

- neofetch
> General: Remove another awk call

- neofetch
Self-explanatory, replaces #779 
N/A
> Misc: Remove all 2>/dev/null instances and put it into one single exec

- ascii/distro/source_mage
- neofetch
- Install Source Mage and figure out how to count packages properly.
- The source code for `gaze` calls a pager when you list installed commands...
> os:  Added support for Source Mage.

- neofetch
This PR adds support for chunkwm - https://github.com/koekeishiya/chunkwm
> Add support for chunkwm (macOS window manager)

- ascii/distro/arya
- neofetch
> OS: Add support for AryaLinux

- neofetch
> Term: Add font support for GNUstep Terminal

- ascii/distro/nurunner
- neofetch
https://nurunner.mkxt.net/
https://github.com/nurunner-linux
> OS: Add support for Nurunner

- config/config.conf
- config/travis.conf
- neofetch
Title.
- Renamed subtitle to `Host`.
- Correctly show `KVM/QEMU`.
> model: Changes to support Virtual Hosts

- ascii/distro/refracta
- neofetch
> OS: Added support for refracta

- ascii/distro/artix
- neofetch
> updated Artix logo with new official logo

- neofetch
Don't know if this is worth a pull request, but I added High Sierra support since it's releasing soon.
> add macOS High Sierra support

- neofetch
Should resolve this issue #855
> distro: fix trueos detection

- neofetch
add Sabotage linux package support
> add Sabotage linux package support

- neofetch
> battery: fix battery detection on Windows

- neofetch
Fixed a minor indent bug I noticed in the `--help` output.
> Fix minor indent bug

- CHANGELOG.md
- neofetch
Self-explanatory. Fixes #928 
N/A
- <s>Should we merge ChromeOS detection on this one?</s>
N/A
> OS: Separate Windows 10 and ChromeOS into its own if clause

- neofetch
XTerms font wasn't being detected correctly. This commit fixes that.
> Correctly handle XTerm.vt100.faceName

- neofetch
self-explanatory
Works only after the user changed and saved some settings.
> term_font: add qterminal support

- neofetch
Add album support for most of the remaining players in the TODO list of #837
pogo
exaile
quodlibet
pragha
amarok
deadbeef
qmmp
xmms2d
mocp
rhythmbox
banshee
mpd
> song: add album for some players

- neofetch
This is my last one for sure xD
Complements https://github.com/dylanaraps/neofetch/commit/94bf52ecd4aa784355ac9fe9ba29c19fb24b62df.
I've setup my own instance of Travis-CI to track errors before committing.
Seems I had cut the lines wrong.  Don't need a backslash when inside `'`.  See shellcheck [SC2004](https://github.com/koalaman/shellcheck/wiki/SC1004).
P.S.:  I'm a sucker for style :P
> kitty: style tweaks on regex

- neofetch
Add album to the song_shorthand example.
> song: update song_shorthand example

- LICENSE.md
- neofetch
> general: update copyright year

- neofetch
> song: audacious: remove audtool, closes #986

- neofetch
A fix for KWin: https://github.com/dylanaraps/neofetch/pull/954#issuecomment-385636957
If you don't like adding the extra case just close this. ;)
> wm_version: add case for kwin

- neofetch
> OS: Add support for Redcore Linux

- neofetch
Sort players alphabetically in config accordingly to the players array in get_song().
Also remove `$` from `iTunes$`. (33d6dd760f79c5ebfff06c42b0e0c88c1ec6c17f)
> song: sort players in config

- neofetch
> song: add support for gmusicbrowser

- completions/neofetch-completion.bash
Add gmusicbrowser to bash completion.
> completion: add gmusicbrowser

- neofetch
> OS: Add support for Regata OS.

- neofetch
https://condresos.codelinsoft.it/new/index.php
> OS: Add support for Condres OS.

- neofetch
As [promised](https://github.com/dylanaraps/neofetch/commit/37bb79460239367e14cecf01f65b76e9ab917c89#r29224581).  I've made sure there is no space around all ENDs in awk statements.
> awk: Space around END

- neofetch
Make some indentations more consistent.
Maybe a bit nit-picky... :ghost:
> misc: indent

- neofetch
> Song: Add Dragon Player and SMPlayer

- neofetch
So I want to add januslinux's logo. Everything works good no issues are have seen
> OS: add januslinux

- neofetch
There is a new SMC emulator https://github.com/acidanthera/VirtualSMC
FakeSMC alternative.
> Improve Hackintosh detection

- neofetch
so basically you get support for 2 package managers that basically nobody uses
but hey it can't hurt ¯\\\_(ツ)_/¯ 
[spm](https://github.com/simoniz0r/spm) support
[puyo](https://github.com/Appadeia/puyo) support
> Add support for puyo & spm

- neofetch
Add support for Namib GNU/Linux.
https://www.namiblinux.org/
> OS: Add Namib GNU/Linux

- neofetch
Add ability to modify the default ":" separator.
> Modifiable info separator

- neofetch
> OS: Add Reborn OS

- neofetch
Detected as Devuan if `lsb-release` is installed. See #1143
> Distro: Add support for Star

- neofetch
Minor changes from #1118. Firing up my Bedrock VM now to work on this further.
> Bedrock Linux support

- neofetch
> general: fix image sizing in VTE terminals.

- neofetch
We've redesigned logo of the distro
> new logo for janus

- neofetch
> ASCII: Add fedora_small

- neofetch
Add support for Strawberry Music Player.
https://www.strawbs.org/
> song: add strawberry player

- neofetch
Add support for Goggles Music Manager and Xnoise Media Player.
https://gogglesmm.dev/
http://xnoise-media-player.com/
> Song: Add support for gogglesmm and xnoise

- neofetch
Renamed januslinux to Ataraxia Linux, kept old names for compatibility. New ascii art!
> januslinux is ataraxia linux!

- neofetch
Add support for [yabai](https://github.com/koekeishiya/yabai) on macOS
> WM: Add support for yabai on macOS

- neofetch
Replace KDE with Plasma.
Fix  #1288
> The KDE was renamed to Plasma

- neofetch
add support for [bonsai linux](http://github.com/mitchweaver/bonsai)
> add bonsai linux support

- neofetch
Add support for [Rectangle](https://github.com/rxhanson/Rectangle) on macOS.
> WM: Add support for Rectangle on macOS

- neofetch
Signed-off-by: Bruno d'Arcangeli <bruno@arcangeli.fr>
> [PATCH] Obarun logo added

- neofetch
https://neptuneos.com/en/start-page.html
> OS: Add Neptune

- neofetch
I added some logos from [pfetch](https://github.com/dylanaraps/pfetch) to neofetch.
I'm not sure that I named them properly though...
> ASCII: Added and updated few small logos

- neofetch
Add macOS Catalina OS detection
> Add macOS Catalina

- neofetch
I'm just following the discussion I continued on the previous old pull request: https://github.com/dylanaraps/neofetch/pull/824
Working like expected and with the changes requested in the previous pull request.
Add Proxmox VE (tested)
N/A
N/A
> Add Proxmox VE

- neofetch
Add support for Muine Music Player.
> song: add muine player

- neofetch
Add support for Pantheon Desktop / Elementary OS music player.
> song: add elementary music player

- neofetch
Adds support for Septor Linux. https://septor.sourceforge.io/
> ascii: add septor linux logo

- neofetch
neofetch --ascii_distro 
couldent display these without "" which annoyed me so i fixed hopefully i dident miss any
> small name changes

- neofetch
- neofetch.1
Add option to display DE version as requested in #1052.
Initially supports only Plasma.
> Add initial support for DE version

- neofetch
Adding the logo of my new distribution
> add Carbs Linux logo

- neofetch
Adds support for KWin on Wayland.
> wm: detect kwin on wayland

- neofetch
- neofetch.1
tittle and other small changes
> added some more info to --help

- neofetch
- neofetch.1
Added ascii logo for openSUSE Leap.
> ascii: Add openSUSE Leap logo

- LICENSE.md
- neofetch
Update copyright years for 2020.
What first year is correct, 2015 or 2016?
> Update copyright years

- neofetch
Support for https://regolith-linux.org
Added OS parsing, name and logo
> Regolith linux support

- neofetch
Updated the Linux Mint ASCII Logo to Match Mint 19.3 and above.
> Update Linux Mint Ascii Logo

- neofetch
> Correct spelling

- neofetch
Add support for [xmonad](https://xmonad.org/)
> WM: Add support for xmonad

- neofetch
> Add more device support

- neofetch
Added Garuda Linux
https://garudalinux.in , https://forum.garudalinux.in
> add garuda linux

- neofetch
_Please Add Support For DarkOs Logo In Neofetch ,_ 
**DarkOs** is a new distribution and it's gonna be released hopefully this month , and we'd be really pleased if you include DarkOs logo In list with the others.
> Add DarkOs Ascii Logo

- neofetch
Added support for olivia player. https://github.com/keshavbhatt/olivia
> song: Add olivia player

- neofetch
I've added a new image backend [pot](https://github.com/SeungheonOh/pot).
New image backend
-
-
> Adding Pot terminal image backend

- neofetch
> pot argument fix

- neofetch
Added detection of ubuntu flavors. Solves #1505
> Detect Ubuntu flavors

- neofetch
Added Ubuntu Cinnamon ascii and flavor detection. Solves #1506.
> Add Ubuntu Cinnamon

- neofetch
Add logo for openEuler system
Add logo for openEuler system
No
No
> Add openEuler

- neofetch
Added wallpaper fetching for LXQt desktop.
> wallpaper: Add LXQt desktop

- neofetch
Reworked the Xubuntu and Lubuntu logos as suggested in #1509
Used suggested colors from #1517, choosed 20 for xubuntu
> ascii: Update Lubuntu and Xubuntu

- neofetch
This one was a bit more tricky.. ;)
> Update Ubuntu Cinnamon logo

- neofetch
This time just the unmodified output from www.text-image.com.
Perhaps not the best, but definitely an improvement. :)
> Update Ubuntu Mate logo

- neofetch
Added LibreELEC logo as requested in #1481.
> Add LibreELEC logo

- neofetch
Fixes #1534 and #1503 
This is the fix confirmed in #1534 plus ignoring comments that is needed to also solve #1503.
> term_font: fix alacritty

- neofetch
second try ;)   much simpler
https://colinduquesnoy.gitlab.io/MellowPlayer/
> add song= support for MellowPlayer using get_song_dbus

- neofetch
Added ascii for Live Raizo. https://sourceforge.net/projects/live-raizo/
> os: Add Live Raizo

- neofetch
> uptime: Fix shorthand off

- neofetch
Added ascii logo for Univention Corporate Server https://www.univention.com/
> os: Add Univention

- neofetch
Added Archcraft OS
Archcraft logo ascii
None
Nothing
> Added Archcraft OS

- neofetch
add the [instantOS](https://instantos.io) logo
> add instantOS

- neofetch
Display Armbian instead of Debian / Ubuntu
> Add Armbian Linux

- neofetch.1
updated distro info to latest.
> update man page

- neofetch
Please merge pull request for new Garuda Neofetch logo.
https://forum.garudalinux.org/t/new-garuda-neofetch-logo-soon/1253
Thank you.
> New Garuda Neofetch Logo

- neofetch
This PR refactors the way Überzug is used, as the old way is deprecated
> Refactor ueberzug

- neofetch
Add support Apple Music and remove iTunes
Add support Music app on MacOS
[issuse 1484](https://github.com/dylanaraps/neofetch/issues/1484)
> Add Apple Music

- neofetch
Add HydroOS distro support
Add HydroOS distro ASCII logo
> Add HydroOS distro support

- neofetch
> Fixes #1636

- neofetch
Added AlmaLinux logo. Resolves #1714
> Add AlmaLinux logo

- neofetch
> added PNM Linux ascii art

- neofetch
See https://hikari.acmelabs.space for more information about `hikari`
> Added 'hikari' to supported WMs

- neofetch
See https://github.com/dylanaraps/neofetch/pull/1617#issuecomment-740655977
> Fix nix mistkae on darwin

- neofetch
> Add distribution AmogOS

- neofetch
I added the ASCII artwork of iglunix to the main file. (https://iglunix.xyz/)
> Added iglunix to ascii art distros

- neofetch
Updated Ubuntu logo as requested in #1750 
> Update ubuntu logo. Closes #1750

- neofetch
Add ASCII Art for my in-progress GNU/Linux distribution
> Add Aperio GNU/Linux information.

- neofetch
Reference: https://www.apple.com/macos/monterey-preview/
> Add macOS 12 to version name list

- neofetch
> Fixes GPU info read error on MINGW64

- neofetch
> Update CyberOS logo to match downstream

- neofetch
Added ascii for Kaisen Linux https://kaisenlinux.org/
> Add Kaisen Linux

- neofetch
Neofetch can now detect river.
> RiverWM support

- neofetch
> Fix Haiku logo (#1812)

- neofetch
Added a pkgin to Package manager programs under BSD
> added pkgin to BSD case

- neofetch
- neofetch.1
I'm done with the ASCII Art, @dylanaraps
> Added VNux GNU/Linux Neofetch Logo

- LICENSE.md
Seems you forgot to update the copyright year in the license file. ;)
> docs: update

- neofetch
Updated the openEuler logo. Closes #1965
new:
old:
> Update openEuler logo

- neofetch
Hello, I'd like to add this entry to Neofetch.
Thanks
New QubytOS logo
None
Nothing
> Added Qubyt OS Logo

- neofetch
Add the Pacstall package manager to Neofetch
https://github.com/pacstall/pacstall
> Add pacstall to package managers
